web/app/actions/GatewayActions.js, web/app/components/DepositWithdraw/BlockTradesGateway.jsx, web/lib/common/blockTradesMethods.js
In the gateway deposit/withdraw drop-downs, don't show coin types the
gateway has disabled (important during OPEN.NSR -> OPEN.NUSHARES
transition).
Update the support email for OpenLedger gateway.
=> Hide unsupported gateway deposit/withdrawal coin types

web/app/components/Exchange/BuySell.jsx, web/app/components/Exchange/ExchangeInput.jsx
Added a component to allow additional logic wrapping the number input type which is being used for buy / sell form.
By checking the next value after key press, this input can prevent duplicate decimals from being added. Resolves [issue #137](https://github.com/bitshares/bitshares-ui/issues/137).
=> Use number input with check on decimal value to resolve duplicate decimal issue

web/app/App.jsx, web/app/assets/stylesheets/_shame.scss
Resolves [issue 163](https://github.com/bitshares/bitshares-ui/issues/163) by adding a windows specific selector for increasing select height.
Before:
After:
Follow up with issue reporter after fix is merged  to ensure the fix was sufficient (I think it should be).
=> Resolve issue 163 (text cut off in some drop downs)

web/app/components/Exchange/MarketHistory.jsx
PR for #66.
This shows the bug identified by users:
This shows the fix:
The solution was to have the scroll bar library being used scroll back to the top of the container on tab change.
=> Resolve Issue #66

web/app/components/Utility/TotalBalanceValue.jsx
Resolves [issue 47](https://github.com/bitshares/bitshares-ui/issues/47).
The problem was the loop was skipping setting assetValues (used to display the drop down values) for the primary asset.
I just removed the if condition. Here is screenshot showing correct values:
=> Resolve Issue 47 - Ensure primary asset shows up in balance calculations

web/app/components/Exchange/OrderBook.jsx
PR for #235 .
Only change market or direction will scroll to top , if reload order will not scroll to top.
=> Resolve Issue #235 - Prevent Auto Return to Top Refresh while Scrolling Down the Open Orders List

web/app/assets/stylesheets/components/_help.scss, web/app/assets/stylesheets/layout/_page_layout.scss, web/app/assets/stylesheets/themes/_theme-template.scss, web/app/components/Account/AccountAssetCreate.jsx, web/app/components/Account/AccountAssetUpdate.jsx, web/app/components/Account/AccountOverview.jsx, web/app/components/Account/AccountPermissions.jsx, web/app/components/Account/AccountPermissionsMigrate.jsx, web/app/components/Account/AccountSelector.jsx, web/app/components/Account/AccountVoting.jsx, web/app/components/Account/AccountVotingProxy.jsx, web/app/components/Utility/HelpContent.jsx
Changes:
Left justify the main body block ([from here](https://github.com/bitshares/bitshares-ui/issues/254#issuecomment-322764255)) which improved the experience in wide screens.
Fixed a bunch of UI margin/padding issues, cleaned up some hard coded CSS. Fixed #254.
---
Details:
Fixed #254:
Other UI padding issue screenshots (which have been fixed in this PR):
1. Extra spacing: 
2. Wrong hovering highlighting area:
3. Misaligned label:
4. No spacing between the input and button:
=> Fix a bunch of UI padding issues

web/app/components/Account/AccountVesting.jsx
This PR resolves [issue 160](https://github.com/bitshares/bitshares-ui/issues/160). This issue was caused by component not triggering updates on account changes.
Vesting balances now update as expected.
=> 160 - ensure that vesting balances are updated when hot switching accounts

web/app/components/Account/AccountVotingProxy.jsx
This PR resolves [139](https://github.com/bitshares/bitshares-ui/issues/139) by ensuring that state is updated when the store passes new props down the the proxy component.
=> 139 - Ensure proxy props changing updates component state

web/app/assets/stylesheets/components/_account.scss, web/app/assets/stylesheets/components/_help.scss, web/app/assets/stylesheets/layout/_page_layout.scss, web/app/assets/stylesheets/themes/_theme-template.scss, web/app/assets/stylesheets/vendors/_foundation_overrides.scss, web/app/assets/stylesheets/vendors/_foundation_settings.scss, web/app/components/Account/AccountAssetUpdate.jsx, web/app/components/Account/AccountPage.jsx, web/app/components/Account/AccountVesting.jsx, web/app/components/Blockchain/Asset.jsx, web/app/components/Chat/ChatWrapper.jsx, web/app/components/Explorer/Assets.jsx, web/app/components/Settings/Settings.jsx, web/app/components/Utility/HelpContent.jsx
@wmbutler @svk31 
Thank you for your comments. This is a follow up PR of #273.  
Feel free to give feedbacks and I'll keep improving this PR.
__Major changes__:
1. expand all `.grid-container` to fit the maximum width (75rem)
2. removed a bunch of inlined padding/margin styles in React
1. removed the 800px width limit in `AccountAssetUpdate.jsx`
2. replaced the inline hard-coded CSS in `ChatWrapper.jsx` with foundation presets
3. rewrote the `split_into_sections` function in `HelpContent.jsx` to remove empty `<p></p>`s (which cause extra magin) and made it easier to read
4. re-arranged some misplaced paddings
5. added left/right paddings for the assets/asset page (in mobile screens)
6. fix CSS issues in the settings page (listed in #273)
__Styling suggestions & todos__:
1. only allow …
=> Fix a bunch of UI padding issues (update)

web/app/assets/locales/locale-cn.json, web/app/stores/AccountStore.js
Three bugs are fixed in this PR:
1. Remove extra comma in locale-cn.json
2. Fix the issue #215 Don't remove the brand new accounts when try to hide them
3. When the current account is hided, change the current account name in the header bar.
=> Fix issue #215

web/app/components/Exchange/PriceChartD3.jsx
Clamping the chart makes the right edge display "now", and doesn't allow displaying the blank future. 
Zooming out will pull right to left until the right edge is "now" (If not already) and then continue pulling the history from left to right.
=> Issue 315: Added clamp to ChartCanvas to right justify the chart

web/app/components/Exchange/PriceChartD3.jsx
Reverts bitshares/bitshares-ui#322.
Reverted after reading the additional discussion in the issue, will leave open to further changes
=> Revert "Issue 315: Added clamp to ChartCanvas to right justify the chart"

app/components/Settings/AccessSettings.jsx, app/routerTransition.js, app/stores/AccountRefsStore.js
Addresses [issue # 279](https://github.com/bitshares/bitshares-ui/issues/279).
This PR causes the init which sets up API server to be called again when user selects a new node so that page does not hard refresh.
=> Iss 279 - When selecting a new Node under Settings -> Access, don't hard reload the browser

app/components/Settings/WebsocketAddModal.jsx, app/components/SyncError.jsx
Resolves [issue #351](https://github.com/bitshares/bitshares-ui/issues/351)
=> Iss 351 - Failed to Sync with API Server UI

app/components/Exchange/ExchangeInput.jsx
Resolves [issue #390](https://github.com/bitshares/bitshares-ui/issues/390). 
I had previously implemented a special input to handle exchange inputs so that I could make sure only one decimal was allowed. This behavior was occurring because of that fix, so I extended the special input further. I needed to do away with the number input type, use a text input, and just discard any inputs that were not numeric or ".".
=> Iss 390 - Price Entry Field Ignores '.' Character When Overwriting Selected Number

app/assets/locales/locale-en.json, app/components/Account/AccountAssetCreate.jsx, app/components/Account/AccountAssetUpdate.jsx, app/components/Exchange/MyMarkets.jsx
Resolves [issue #311](https://github.com/bitshares/bitshares-ui/issues/311).
User now has toggle for whether or not the asset should be hidden, which is stored in description:
Hiding the asset will cause it to be hidden in search / markets:
=> Issue 311 - Allow for hiding user issued assets

web/app/assets/locales/locale-en.json, web/app/components/Exchange/Exchange.jsx, web/app/components/Exchange/PriceChartD3.jsx, web/app/components/Exchange/PriceStat.jsx
#315 Fix. Add Toggle In Settings Dropdown.
=> Issue 315 - Add Chart Clamp To Settings Dropdown

app/components/DepositWithdraw/BlockTradesGateway.jsx
The email support@openledger.info is no longer checked, they have migraded to freshdesk. Replacing the email address with the link to their support portal.
=> Update openledger support info

app/components/Transfer/Transfer.jsx
=> Fix #460 transfer qty validation issue

app/idb-helper.js, package.json
Running a hot-reload server with `npm start` causes a JS exception due to how react-hot-reload rewrites the function defined within the `ChainEvent` constructor, changing it's scope. Here's what it ends up with currently, so fails when `callback(event)` is hit:
```
var ChainEvent = function () {
function ChainEvent(existing_on_event, callback, request) {
var _this = this;
_classCallCheck(this, ChainEvent);
this.event = function () {
return _this.__event__REACT_HOT_LOADER__.apply(_this, arguments);
};
}
_createClass(ChainEvent, [{
key: "__event__REACT_HOT_LOADER__",
value: function __event__REACT_HOT_LOADER__(event) {
if (event.target.error) console.error("---- transaction error ---->", event.target.error);
//event.request = request
callback(event);
if (existing_on_event) …
```
=> Fix development server issue due to hot-reload rewriting

app/components/Transfer/Transfer.jsx
Resolves #533 
One small note here - if there is a delay in the API response, the form may not clear immediately. It will clear as soon as the user gets the success message, though.
=> Issue 533 - Clear transfer form once completed

app/components/Wallet/WalletManager.jsx
Resolves #484 
The reported behavior was because backup store was not being reset when wallet changed. This puts backup in pristine state when user change wallets.
=> Iss 484 - Reset backup store when wallet is changed

app/assets/stylesheets/layout/_page_layout.scss, app/components/Account/AccountOverview.jsx, app/components/Blockchain/Asset.jsx, app/components/Utility/Tabs.jsx, app/lib/common/tableHeightHelper.js
This change ensures that tables will always have the correct height, being at least fully extended to the bottom of the container.
To use, add `app-tables` to the `grid-content` container, and import `tableHeightHelper` into the component. There is a JS update that needs to get applied in both an interval and on tab change.
Resolves #496
=> iss 496 - ensure tables retain correct height

app/api/apiConfig.js
[UPDATE] Add Thailand RPC Node to the WS_NODE_LIST
Line 27: {url: "wss://bitshares.apasia.tech/ws", location: "Bangkok, Thailand"},
=> Updated apiConfig.js

app/assets/locales/locale-en.json, app/assets/stylesheets/components/_account.scss, app/assets/stylesheets/layout/_page_layout.scss
Took padding out of the new tables in an effort to get closer to the final look for #630. My commit brought the padding in for the new voting screen and the dashboard, but it created some issues on the various explorer pages. Nothing serious, but they do need to be looked at before this is released.
=> #630 removed padding from Dashboard and Voting

app/components/Account/AccountOverview.jsx
It appears sortFunctions declared outside the component class was unable to access state after the component was rebound after navigation. Simplest solution I could find was moving the sort functions inside the class, similar to how Blockchain/Asset.jsx does it.
=> Bug fix #689 - Sorting portfolio assets

app/components/Modal/BorrowModal.jsx
[Resolves issue #718](https://github.com/bitshares/bitshares-ui/issues/718)
The problem here was that blockchain updates were causing the form state to get totally reset. I changed this to keep the existing user entered values and redo the validation.
@svk31 There may be a cleaner way to do this but this ensures the values are preserved.
=> Update borrow modal state reset

app/assets/locales/locale-en.json, app/components/Dashboard/MarketCard.jsx, app/components/Exchange/MyOpenOrders.jsx, app/components/Utility/MarketPrice.jsx
Resolves [issue #698](https://github.com/bitshares/bitshares-ui/issues/698)
@svk31 I added the code you put on staging here, thinking as it's no change it will merge nicely.
=> #698 - display quoted price in open orders

app/components/Exchange/DepthHighChart.jsx
This fixes issue #732 by changing the color of the settlement line if the order book is reversed for a smart coin.
=> Fix Issue #732 - Settlement Line Color

app/components/Account/AccountOverview.jsx, app/components/Exchange/MyOpenOrders.jsx, app/components/Utility/FormattedPrice.jsx, app/components/Utility/MarketPrice.jsx
Resolves acceptance bugs for [issue 698](https://github.com/bitshares/bitshares-ui/issues/698). Adds missing footer column and resolves price quote inversion issue by allowing to respect invert prop.
=> Missing td, fix price inversion issue for quote

app/assets/stylesheets/themes/_theme-template.scss, app/components/Settings/AccessSettings.jsx
Sets the API status colors to a more theme specific color.
Using the Ask, Bid and Call colors for the current theme.
=> Fix Issue #722 - Set more theme specific API Status colors.

app/api/apiConfig.js
Addition to RPC Nodes list for the location New York, USA. 
wss://us-ny.bitshares.apasia.tech/ws
adding line 33 (moving all for 1 below)
{url: "wss://us-ny.bitshares.apasia.tech/ws", location: "New York, USA"},
=> Add RPC Node wss://us-ny.bitshares.apasia.tech/ws

app/stores/SettingsStore.js
There were two `BRIDGE.BCO` in the `topMarkets` array. Found this when customizing self-hosted wallet.
=> Remove duplicated asset in topMarkets

app/assets/locales/locale-en.json
Found this typo(?) when trying out the function.
=> Fix invalid signed message signature notice in English

app/api/apiConfig.js
This is the onboarding faucet.
Stats and settings can be found here:
* https://bitshares.eu/referral/onboarding/onboarding.bitshares.foundation
=> New faucet according to infrastructure worker proposal

app/components/Modal/SendModal.jsx, app/components/Utility/AmountSelector.jsx, app/components/Utility/FloatingDropdown.jsx
So the SendModal dialog 'Fee' and 'Quantity' dropdowns don't hide items beyond the second.
This fixes #893.
As a note, this could probably be simplified by just setting `style="scroll: auto"` on the `FloatingDropdown` component.  However, the current behaviour was explicitly added in 4ac20478 so I erred on the side of caution.
=> Add `scroll_length` property to FloatingDropdown and AmountSelector

app/components/Modal/QrcodeModal.jsx
Fix #938: Add white background to qrcode
=> Fix #938: Add white background to qrcode

app/assets/stylesheets/themes/_theme-template.scss
Fixes issue #956 
- Background color needs to be defined on <option> element to be applied to windows light wallet
=> Fix for Issue #956 - Theme Color Issue

app/components/Modal/BorrowModal.jsx
Changed to steps of 0.01 vs 0.05.
- Fixes #900
=> Increase precision of Collateral Slider in BorrowModal

app/components/Blockchain/Fees.jsx, app/components/Utility/EquivalentValueComponent.jsx
Added a new prop `fullDecimals` in `EquivalentValueComponent`. Defaults to false, when true it will show full precision instead of only 2 decimal digits.
=> Show full precision on fee schedule and always show fee in BTS, fix 992

resources/electron_context_menu.js, resources/index.js
I was having a heck of a time getting the native build to properly pull in the `electron-context-menu` dependency (followed several different guides), so I added it manually to the resources directory (and removed a few un-needed bits along the way).  As it's MIT licensed I added the copyright notice at the top as should be done.
If someone can point me at the proper way of doing this I'll modify the PR, but it seems that the Electron shell itself doesn't inherit the dependencies of the inner app.
Also, is it possible to pull in the current version number dynamically?  That could be added to the 'Bitshares' string in the context menu.
This fixes #973.
=> Electron build - Add context menu

app/assets/stylesheets/components/_exchange.scss, app/assets/stylesheets/themes/_theme-template.scss, app/components/Exchange/ExchangeHeader.jsx, app/components/Exchange/PriceStatWithLabel.jsx, app/components/Layout/Header.jsx
- Relocated the shuffle button to be inline with the stat label
- Added star market button to the trading pair stat
- Prevented the latest and 24hr volume stats from changing colour
- On browser window resize, updated the order in which stats are hidden
- Updated header so that the 'create acount' link doesn't wrap so early
=> Exchange header tweaks

app/api/apiConfig.js
According to the bitshares infrastructure worker, these are the first loadbalanced nodes provided by Blockchain Projects BV and funded by the BitShares DAC thanks to BTS holders.
Read more: https://bitsharestalk.org/index.php/topic,25291.0.html
=> New API endpoints

app/assets/stylesheets/components/_header.scss, app/assets/stylesheets/themes/_theme-template.scss, app/components/Layout/Header.jsx
Wallet account:
Login/pass account:
**Changes**
- Add additional dropdown with Accounts list and Account link if user is on Wallet Account mode
- Remove Accounts list from hamburger menu
- Remove Account link if user in Wallet Account mode
- Fix height of hamburger block (floating pixel)
- Increase paddings of user account name block to make it looks better
- UPD: Remove current account from accounts list
**Tested on MacOS in all media queries **
- Chrome
- Opera
- Firefox
- Safari
Btw: I'm new on bitshares-ui so I'm open for advices because I'm going to do a lot of work in future. 
Btw 2: If make window size is small the name and hamburger jumps on the next line and partially disappear. I have posted an issue about that: #1083
=> Feature: Accounts dropdown 1028

app/assets/stylesheets/_shame.scss, app/components/Blockchain/TransactionConfirm.jsx, app/components/Forms/AccountSelect.jsx
Before: 
After: 
Changes: 
- Fix position and width of propose
- Provide an additional `full-width` class for bts-select
- Provide an ability to apply className for AccountSelect component
Tested on MacOS (all media queries):
- Chrome
- Firefox
- Opera
- Safari
=> Fix position of propose from on transaction confirmation #1071

app/components/LoginSelector.jsx
The bug was if user do Login on `/create-account` page except `/` (home) after Login he stays on this page and see `Welcome to Bitshares` message except be redirected to dashboard 
Tested on Mac:
- Chrome
- Firefox
- Safari
- Opera
Redirect was tested by the following use cases:
=> Do redirect to user Portfolio after Login #1068

app/components/Modal/SendModal.jsx, app/components/Transfer/Transfer.jsx, app/lib/common/trxHelper.js
This modifies the `_updateFee` method of `SendModal` and `Transfer` to check the requirements stated in the issue #977.
After fetching the initial fee amount,  if the requirements are met, it changes the `fee_asset_id` to the selected asset and re-updates the fee.
=> Feat #977: Gracefully handle send operation for accounts with 0 BTS

app/assets/stylesheets/base/_fonts.scss, app/assets/stylesheets/components/_exchange.scss, app/assets/stylesheets/themes/_theme-template.scss, app/assets/stylesheets/vendors/_perfect-scrollbar.scss, app/components/Exchange/OrderBook.jsx, package.json
Screenshots [here](https://github.com/bitshares/bitshares-ui/issues/972#issuecomment-361022310)
This adds a new dependency, [react-sticky-table](https://github.com/henrybuilt/react-sticky-table). 
I would have had to re-implement pretty much the same thing without it.
I took the liberty to add two feature not requested in #972 :
+ A lock button that is on by default to maintain the order book centered as it gets updated.
+ The ability to click on the spread to display a percentage
=> Feat #972: Joined vertical order book

app/components/Account/AccountSignedMessages.jsx, app/components/Account/SignedMessage.jsx
The component only takes the signed message and can verify itself. Idea is to allow reuse everywhere where verification might be wanted
=> introduced a SignedMessage component

app/assets/locales/locale-en.json, app/components/Blockchain/Asset.jsx, app/components/Utility/FormattedTime.jsx
For issue https://github.com/bitshares/bitshares-ui/issues/766
Adds settlement offset and delay to the assets page in a manner similar to cryptofresh. As a small fix, also adds a dash to the global settlement price when the asset has black swanned.
=> 776 add force settlement offset and delay to asset page

app/components/Account/AccountOverview.jsx
**Changes:**
- Update total balance of Portfolio. Now it displays only Active Assets Total Value (Hidden assets excluded)
- Add `Total` for `Hidden` assets like on `Active` tab.
**Tested on MacOS on all media queries:**
(Beginning from 900px and lower `Total BTS` column excluded from the table and I didn't change it. So Total Value of hidden assets visible only if screen size is bigger than 900px )
=> Deduct Hidden Assets from Portolio Total and provide Total for Hidden Assets #1061

app/components/Dashboard/DashboardAccountsOnly.jsx, app/components/Dashboard/DashboardList.jsx
**Changes**
- Provide ID for Contacts/Accounts tables on `/accounts` page
- Fix check for isMyAccount (it was wrong for login/password accounts so I've added the following check: 
```
let isMyAccount = AccountStore.isMyAccount(account) || accountName === passwordAccount; // password account from AccountStore.getState().passwordAccount
```
@svk31 Please take a look at this fix. I suppose it's fine. I've found this check on another sides of our project. If it's wrong please help me to understand why and what is the right way to check `isMyAccount` for login/password accounts. Because for now `AccountStore.isMyAccount` works only for Wallet accounts.   
The last change fix this: (You see your own account in Contacts expect seeing on Accounts tab)
To this:
**Tested on MacOS**
=> Display Accounts ID on Accounts Page #1091

app/assets/stylesheets/_shame.scss, app/assets/stylesheets/components/_forms.scss, app/assets/stylesheets/components/_header.scss, app/assets/stylesheets/themes/_theme-template.scss, app/components/Account/CreateAccountPassword.jsx, app/components/Blockchain/Asset.jsx, app/components/Layout/Header.jsx, app/components/Wallet/WalletManager.jsx
Related to #1082:
- Implemented updated UI styles
- Removed redundant 'create account'
- Burger menu displays all the time now
- Removed settings from the header bar because it is in the burger menu
- 'Create account' link shown in burger menu if the user is logged out
- 'Dashboard' link shown in burger menu if the user is logged in
- Removed the big lock/unlock icon
- Added a small lock/unlock icon next to username to tell if logged in or not
- Updated hamburger icon to bitshares blue
- Have added functionality to truncate the username when it's too long for the resolution
- Fixed #1090
- Aligned page title on 'restore backup' view to left
- Tested both login/password and local wallet accounts
=> Responsive on boarding for #1082

app/assets/locales/locale-en.json, app/assets/stylesheets/themes/_theme-template.scss, app/components/Dashboard/DashboardList.jsx
**Tested on MacOS:**
Changes I made:
1) Fix divider between Hidden/Shown accounts
2) Do not display divider if hidden accounts doesn't exist
3) Do not display Show/Hide button if hidden accounts doesn't exist
4) Add an ability to add contact back and fix icon
=> Account section improvements #1130

app/App.jsx, app/assets/locales/locale-de.json, app/assets/locales/locale-en.json, app/assets/locales/locale-es.json, app/assets/locales/locale-fr.json, app/assets/locales/locale-it.json, app/assets/locales/locale-ko.json, app/assets/locales/locale-ru.json, app/assets/locales/locale-tr.json, app/assets/locales/locale-zh.json, app/assets/stylesheets/components/_settings.scss, app/assets/stylesheets/themes/_theme-template.scss, app/components/BrowserNotifications/BrowserNotifications.jsx, app/components/BrowserNotifications/BrowserNotificationsContainer.jsx, app/components/Settings/Settings.jsx, app/components/Settings/SettingsEntry.jsx, app/stores/SettingsStore.js, package.json
*Tested on MacOS*
1) Now when user opens app for the first time browser will ask him to allow notifications
2) For now supported only "transfer to me" notifications but it's scaleable and easy to track more events and fire notifications for them.
3) If user disabled permissions for Notifications on Browser Settings (or just click Deny when browser ask for permission to send notifications) and user has "Allow browser notifications" on settings I display the following message: 
(Link opens google - turn on browser notifications, on new tab)
If Notifications disabled there is no any message:
4) User is able to disable specific event (for now we have only one event)
=> Browser notifications #686

app/components/Account/AccountPermissions.jsx
Core bug is fixed.
Removed "sign as owner" to force signing with owner key, as this will be fixed in the backend and this function will not be needed anymore here.
//Edited by @abitmore: this PR is for #754
=> Remove "sign as owner" in permission change

app/components/Explorer/Accounts.jsx, app/components/Explorer/Assets.jsx
Fixes Issue #1070 
- Loading Indicator when fetching Accounts search term
- Loading Indicator when fetching Assets cache list
Assets are cached on navigation to the page and loaded by batches of 100 trough the API call of `list_assets`, but we can never know how many there are until we've done this at least once.
A cached value of total assets is stored during the load, and updated if this increases. While the value of the stored number is less than the loaded, a loading indicator will be visible. During the first load a default number of 3000 assets will be set. I'm subtracting 100 from the previous cached total, as I'm unsure if this value would ever decrease? An issue for this has been created on core level here https://github.com/bitshares/bitshares-core/issues/688
=> Fix Issue #1070 - Loading Status on Assets/User Search

app/components/Blockchain/Asset.jsx
Remove invalid negative margin on Asset `Price Feed Data` Tab
=> Hotfix - Remove invalid negative margin on table

app/components/Modal/DepositModal.jsx
Unset `selectedGateway` when no gateway is returned for an asset.
=> Issue 1248 - Broken asset/gateway logic

app/components/Dashboard/MarketsTable.jsx
@svk31 please make sure on likes `333` and `337` I do correct check for bit* asset. If you can advice the better way just let me know.
=> Fix ability filter and provide an ability to filter by pair #1255

app/components/Account/AccountOverview.jsx
=> #1271 Add an ability to filter portfolio by asset name

app/components/Layout/Header.jsx
Issue was that 'toggle' handler was on parent element except be on account name. That fired dropdown open when it closes
=> #1265 Fix accounts list toggle

app/actions/AccountActions.js, app/components/Account/AccountSelector.jsx, app/components/Dashboard/DashboardAccountsOnly.jsx, app/components/Dashboard/DashboardList.jsx, app/components/Explorer/Accounts.jsx, app/components/Transfer/Transfer.jsx, app/components/Utility/TypeAhead.js, app/stores/AccountStore.js
Task: #1173
**Tested on MacOS**
**Changes**:
- Add Contacts API on AccountStore/AccountActions
- Replace Accounts Linking for Accounts Contacts on Explorer/Accounts
- Replace Accounts Linking for Accounts Contacts on Account / Contacts page
- Use isContactsList as flag for DashboadList instead of showMyAccounts (it's more logical, on previous version we used showMyAccounts to detect "Accounts"/"Contacts" tabs.
- Add typeahead for Send modal (user can see there his contacts. If contacts list empty typeahead is disabled because it looks awful and no sense when no contacts)
=> Contacts Improvements #1173

app/actions/SignedMessageAction.js, app/actions/WalletActions.js, app/actions/WalletUnlockActions.js, app/api/ApplicationApi.js, app/components/Account/CreateAccount.jsx, app/components/Blockchain/MemoText.jsx, app/components/Blockchain/Transaction.jsx, app/components/Layout/Header.jsx, app/components/PrivateKeyView.jsx, app/components/Wallet/ImportKeys.jsx, app/stores/WalletDb.js, app/stores/WalletUnlockStore.js
WalletUnlockActions.unlock() was adjusted and now does
- requires a catch (for user cancellation)
- finally handler works as intended
Here is the console output of the example mentioned in the issue:
unlock cancelled:
unlock successfull:
The actual changes contain the edits from @gibbsfromncis and additionally .catch(() => {}); everywhere where unlock() was used. The rest is reformatting from the commit hook I think.
=> fix wallet unlock behavior #1283

app/actions/SettingsActions.js, app/components/Exchange/BuySell.jsx, app/components/Exchange/Exchange.jsx, app/components/Exchange/ExchangeContainer.jsx, app/stores/SettingsStore.js
Task: #1331
*Tested on Mac OS*:
Changes:
- Add option "1 year" to time select list
- Set default expiration "1 year"
- Display Calendar above the field
- Store last selected expiration on localStorage (all except Specific time. There is no reason to store specific time and then make a checks is it past time or future etc.)
@svk31 please accept my PR to Calendar first - https://github.com/bitshares/react-datepicker2/pull/1
I've added an ability to set position of calendar using props.
=> Issue #1331 - Order Expiration Updates

app/components/Modal/DepositModal.jsx, app/lib/common/assetGatewayMixin.js
Closes #1289 
This uses gateway auto select logic shared by the withdrawal modal. This will auto select whatever gateway has the greatest balance for the selected asset, or default to the first one.
This logic can be modified via an override fn, but I think defaulting to most used and falling back to the first one makes sense.
=> Iss 1289 - Deposit Modal - Autoselect Gateway when available is 1

app/App.jsx, app/actions/GatewayActions.js, app/api/apiConfig.js, app/components/Account/AccountDepositWithdraw.jsx, app/components/Account/BalanceWrapper.jsx, app/components/Dashboard/SimpleDepositWithdraw.jsx, app/components/DepositWithdraw/DepositWithdrawAssetSelector.js, app/components/DepositWithdraw/blocktrades/BlockTradesGatewayDepositRequest.jsx, app/components/Exchange/Exchange.jsx, app/components/Modal/DepositModal.jsx, app/components/Modal/WithdrawModalNew.jsx, app/help/en/gateways/winex.md, app/help/en/toc.md, app/lib/common/assetGatewayMixin.js, app/lib/common/blockTradesMethods.js, app/lib/common/gatewayUtils.js, app/lib/common/gateways.js, app/stores/GatewayStore.js
This PR contains many changes and are also part of #1244 (Backend Cleaning). It contains a starting base for unifying adding new gateways in a simpler fashion than having to write a whole new section, using the new Modal Deposit/Withdraw.
A lot of redundant code has been moved or removed.
- Adding Winex
- Fix Deposit Address checker (was always checking against OL)
- Updating Help to contain Winex information
- Moving backingAsset calls to one specific section
- Replacing backingAsset calls with cache
- Only update backingAssets when app starts
- Initial Move of common Gateway Settings
- Many Gateway specific code sections are replaced to support general gateway additions
- Update Deposit/Withdraw Modals
- Always display deposit warning regardless of gateway.
- General code cleaning and …
=> Issue 1275 - Gateway Update to support Winex

app/assets/locales/locale-en.json, app/components/Account/RecentTransactions.jsx, app/components/Blockchain/BlockTime.jsx, app/components/Blockchain/Operation.jsx
View full date in account transaction
- Changes to BlockTime and Operation
- Adding 'fullDate' prop to BlockTime + Operation
- View fullDate based on fullDate true/false
- Additions to Counterpart.Localize
- Adding `format: "full"` to view full date incl. timezone
=> Issue 1396 - Full Date in Account Transaction

app/components/Blockchain/Asset.jsx, app/components/Utility/HelpContent.jsx
Fix for #1319 
Limited a greedy regex that was wiping out the description on the asset view. I suspect it only occurred on production due to whitespace/multiline minification.
=> #1319 Missing Asset Description

app/components/Layout/Footer.jsx
Actual change takes only a few lines (271-280), the rest is changed by formatting plugin.
=> #1446: Showing "Switch Node" popup only on node description hover, but not the Help button.

app/components/Wallet/WalletUnlockModal.jsx
I failed a call order and the unlock modal doesn't resolve whatever called it.
The symptom is that you have to click again after unlock.
=> 1437 - Fix calls order fail

app/components/Blockchain/Fees.jsx
Since the fee percentage the network keeps is dynamic and settable in global properties, it should be read from the global properties object (2.0.0).
=> Fix #1517 - Remove hardcoded network fee percentage

app/components/Exchange/ExchangeHeader.jsx
Exchange header tooltip wasn't correct for the feed price, as it showed the value of settle price.
=> Issue 1516 - Exchange Header Tooltip Issue

app/assets/locales/locale-en.json, app/components/Blockchain/Operation.jsx, app/components/Blockchain/ProposedOperation.jsx, app/components/Utility/TranslateWithLinks.jsx
Includes Asset links inside transaction translations for accounts.
=> Issue 1535 - Enable asset links in transactions

app/components/Account/AccountAssetUpdate.jsx
Use the correct assets precision for CER
=> Issue 1534 - Use correct asset precision for Core Exchange Rate update

app/actions/SettingsActions.js, app/components/Exchange/Exchange.jsx, app/stores/SettingsStore.js
**Tested on MacOS:**
**Issue:** #1448
=> #1448 Display walkthrough when user opens exchange for the first time

app/assets/stylesheets/themes/_theme-template.scss, app/components/Modal/BorrowModal.jsx
Enables locking CR vs Debt and vice versa.
Default is locked Debt value.
=> Issue 1496 - Locking CR / Debt values on Short Position

app/components/Account/AccountSelector.jsx, app/components/Account/AccountVoting.jsx, app/components/Account/RecentTransactions.jsx
Disables Typehead on AccountSelector for proxy voting to allow empty proxy name
=> Issue 1525 - Clear Voting Proxy

app/assets/locales/locale-en.json, app/components/Blockchain/Operation.jsx, app/components/Exchange/MyOpenOrders.jsx
Adds order id consistantly on open orders and transactions history.
=> Issue 1557 - Use order ID consistently

app/components/Blockchain/ProposedOperation.jsx
Removes `decimalOffset` on proposed transactions
=> Issue 1556 - Decimal Proposed Transaction Precision

app/components/Account/AccountAssetCreate.jsx
- Allow numbers in asset name
Requires BitsharesJS PR https://github.com/bitshares/bitsharesjs/pull/22
=> Issue #1566 - UI Update for BSIP-0037

app/assets/locales/locale-en.json, app/components/Blockchain/Operation.jsx, app/components/Blockchain/Transaction.jsx
Adds support for the following new OPs
- asset_claim_pool: 47
- asset_update_issuer: 48
=> Issue #1547 - Support New OPs 47 + 48

app/assets/locales/locale-en.json, app/components/Blockchain/Operation.jsx, app/components/Blockchain/Transaction.jsx
Fixes issue when order ID is not yet available for notification component
Removes TX ID #x label on transactions without TX IDs.
=> Issue 1605 - Missing orderId for notifications

app/assets/stylesheets/_shame.scss
Op table first td had a min-width. Rendered width depended on content of second td leading to misalignment:
Changed to fixed width:17rem which should be ok:
=> Slight Operations Table Display Fix

app/components/Exchange/MyOpenOrders.jsx
Opted for using `time_format` from utils.js since it's already imported; manual integration testing passed.
=> #1529 Expiration Time display in Open Orders

app/assets/locales/locale-en.json, app/assets/locales/locale-ru.json
Removed "order" parameter from _proposal.limit_order_buy_ and _proposal.limit_order_sell_ because it's undefined [here](https://github.com/bitshares/bitshares-ui/blob/develop/app/components/Blockchain/ProposedOperation.jsx#L179)
=> Fix undefined order property

app/components/Account/RecentTransactions.jsx, app/components/Blockchain/Operation.jsx
- Remove asset decimal offset on account activity
- Fixes activity table visual issue
=> Issue 1676 - Asset decimal offset and table fixes

app/assets/locales/locale-en.json, app/components/Settings/AccessSettings.jsx, app/routerTransition.js
- implements #1701
- fixes bug when no connection can be established (url in urlChangeCallback is then undefined)
- urls that fail are removed from ping map
- adds doQuickLatencyUpdate to reping a subset of nodes, currently unused 
=> Implements #1701

app/assets/locales/locale-en.json, app/components/Blockchain/Asset.jsx, app/components/Modal/BorrowModal.jsx
Applies BSIP 38 to the UI to allow `Target Collateral Ratio`.
An update of the CR still requires the CR to be changed, either in Collateral or Debt.
Below is a view of the new update, including the error mentioned.
=> Issue 1575 - Adding UI for Target CR on Modal

app/branding.js
Looks like this code is not correct
`"RUDEX" in ["OPEN", "RUDEX", "WIN", "BRIDGE", "GDEX"]`
returns false.
Because of this bug RuDEX and OpenLedger gateways have empty tabs on this page - https://develop.bitshares.org/#/deposit-withdraw
http://prntscr.com/k9lymf
=> Fix gateway enabling

app/assets/locales/locale-en.json, app/assets/stylesheets/components/_modal.scss, app/components/Blockchain/Transaction.jsx, app/components/Modal/BorrowModal.jsx
Some cosmetic issues was found after the previous PR. 
This PR fixes those.
- Adds Target CR to TX details
- Fixes checkbox not working properly on modal
=> Issue 1575 - Fixes for Target CR

app/components/DepositWithdraw/blocktrades/BlockTradesBridgeDepositRequest.jsx
A missing checker for `amount_to_withdraw` made any user input on the withdraw section of BlockTrades impossible. 
Took some time to find this trigger in the code.
=> Issue 1628 - BlockTrades Withdrawl Issue

app/api/apiConfig.js, app/components/Layout/Footer.jsx, app/routerTransition.js
#1521
- remove duplicate doQuickLatencyUpdate
- remove bug that you dont connect to your selected one if not autoselction
Members of chinese community gave feedback on connection strategy, adjustments were made:
- askToReconnectAfterSeconds in footer increased to 10 seconds
- beSatisfiedWith is now a map according to AccessSettings display and accepts worse ping to stop pinging all
=> More nodes and connectivity bugfix

app/components/Dashboard/MarketsTable.jsx
MarketsTable will fail on update() when props.markets are empty.
Tested on Mainnet + Testnet (which failed before)
=> Issue 1800 - Check that we have markets to use before updating MarketsTable

app/components/Account/AccountSelector.jsx
The AccountSelector does not allow for empty strings without this.
I would recommend merging this at the same time as #1806 since it improves the proxy change user-friendliness.
=> Fix AccountSelector not propagating change to empty string

app/assets/locales/locale-en.json, app/components/Blockchain/Operation.jsx
Closes #1785
Thanks @abitmore 
Instant settlement (the feature to implement):
Normal settlement for comparison:
=> #1785 - Add instant settlement description in account activities

app/components/Settings/Settings.jsx, app/components/Wallet/WalletChangePassword.jsx
Closes #1856 
I also removed the "Password" entry from the settings menu when using password login as `WalletDb.changePassword` only supports local wallet.
=> #1856 - Fix wallet password change form

app/components/Explorer/Explorer.jsx
Tested on MacOS:
Issue #1816 
Replace old Tabs for Tabs from Style Guide (Ant Tabs)
=> #1816 Replace Explorer Tabs for new Ant Tabs

app/lib/common/gatewayMethods.js
When `assetWithdrawlAlias` was missing in the `gatewayStatus` object the function to fetch new deposit addresses would fail.
This would be noticed when a new address was requested for BlockTrades in-wallet transactions on the Buy Modal.
=> Fixes 1905 - Buy Modal error

app/actions/BackupActions.js
Issue was in missed field in Safari because of browsers specification
**Tested on the following browsers**:
_Please make sure you tested your feature in all following browsers_
Issue: #1125
=> #1125 Fix file restore on Safari

app/components/Blockchain/TransactionConfirm.jsx
The fix is pretty simple. The issue is when I work on Modals replacement I did replace of `<Translate>` to `counterpart.translate`. 
`counterpart` do crash if property needed for translaction is missed. `<Translate>` doesn't. 
Issue: #2088
=> #2088 Fix missing property message to empty

app/components/Account/RecentTransactions.jsx, webpack.config.js
Closes #2168
After investigation I realized the URL is hardcoded in bitshares-report. Either case, it is now pointing to infrastructure ES cluster.
Took 0.5
=> #2168 Switch ES exporter to infrastructure nodes, remote ui reference

app/components/Dashboard/SimpleDepositBlocktradesBridge.jsx, app/components/Exchange/Exchange.jsx
Closes #2180 
Deposit asset name wasn't updating correctly, fixed.
Make sure we have an updated backingAsset list once the exchange loads to prevent caching of older data.
=> Issue #2180 - Fixes to Quick Deposit

app/components/Wallet/WalletUnlockModal.jsx
Closes #2216 
It was a little bit hard to discover why ant select is not showing but finally I found issue in `z-index`. The select dropdown `z-index` was lower than modal `z-index`. Btw I use custom `z-index` for Login modal to show it over other modals when user try to do any operation when his account is not unlocked.
=> #2216 Fix login modal zIndex

app/branding.js
Bug fix for issue 1850:
https://github.com/bitshares/bitshares-ui/issues/1850
The function did not return any symbols if the chainId was from a custom private testnet.
=> bug fix initialization on private testnets.

app/components/Blockchain/Operation.jsx
Fix #2224 
This bug is triggered when Operation comes from TransactionConfirm.componentWillReceiveProps, <this.props.result> would be undefined in this case.
=> Issue 2224 bug fix.

app/assets/locales/locale-en.json, app/components/Account/AccountPortfolioList.jsx
Closes #2292 
- Disable Borrow link when in GS. Shows information tooltip instead.
- Inludes various code cleaning and testing with new Tooltip from Style Guide. 
An asset in GS can't be updated, nor borrowed, and `Borrow` on Dashboard should be disbaled for such assets.
=> Issue 2292 - Disable Borrow on Dashbaord for GS Assets

package.json
Closes #2101 
Commits:
https://github.com/bitshares/bitshares-ui-style-guide/commit/3cd9497870a1bc6ae94aca735c5a189522a8ea71
https://github.com/bitshares/bitshares-ui-style-guide/commit/3f03dc64c5745767ac6b90642b6c3ac666e44cfc
New AddonBefore & AddonAfter:
=> #2101 Update style-guide version to the latest

app/lib/common/paperWallet.js
Closes #2319 
- Changed order of naming.
- Adding private to private key wallet by default.
=> Issue 2319 - Fix paperwallet naming

app/assets/stylesheets/themes/_theme-template.scss
Closes #2344 
Seems like the styles were accidentally removed by commit:
https://github.com/bitshares/bitshares-ui/commit/cc2ecfa85812fdb9a340c80dc3ba71ed501cf8a9#diff-300e3a80c04e0dc255cd3f2f95a9d366 
@gibbsfromncis , please take a look and confirm I'm not losing anything.
=> Return missing styles back

app/components/Blockchain/BidCollateralOperation.jsx, app/components/Utility/FormattedPrice.jsx
Closes #2290 
Adds ignorePriceFeed prop to ignore current price for asset pair when doing collateral debt visual price
=> Issue 2290 - Add prop "ignorePriceFeed" to FormattedPrice

app/components/Showcases/ShowcaseGrid.jsx
Fixes: https://github.com/bitshares/bitshares-ui/issues/2324 . On [this](https://github.com/bitshares/bitshares-ui/blob/develop/app/components/Showcases/ShowcaseGrid.jsx#L23) line it calls np.props.currentAccount, but it is actually np.currentAccount, as np stands for next props. I removed the .props, and everything works as expected.
=> Issue 2324 - Fixes Switching Accounts In Spotlight Crashes

app/components/Blockchain/TransactionConfirm.jsx, app/components/Wallet/WalletUnlockModal.jsx
Closes #2322 
I fixed the feature to use the enter key for the login and confirm modals. On the login modal it will submit only when you click the submit button, or if your typing in the private key/password field and hit the enter key, using the built in onPressEnter for Antd's Input Component. On the confirm modal I added a onkeyup event listener to listen for a keyCode 13, or the enter key, and when it get's a 13 code it will confirm the transaction.
=> Issue 2322 - Enables the enter key for login and confirm modals

app/components/Blockchain/Asset.jsx
Closes #2359 
When an asset has no feeds (ABIT.CNY in this case) there will be an invalid SettlePrice object, making the application crash.
Line 100 on `Asset.jsx` was added to hide warning about failing object creation of `CallOrder` when feedPrice was missing.
=> Issue 2359 - Catch invalid SettlePrice object

app/assets/stylesheets/themes/_theme-template.scss, app/components/Layout/Footer.jsx
Fixes https://github.com/bitshares/bitshares-ui/issues/2329 by checking if the node region starts with TESTNET. This is how it is indicated in the WS_NODE_LIST array for example:
{ "region": "TESTNET - Northern Europe", }
If the node has a property of region and it starts with TESTNET, as well as being connected, then show the word TESTNET next the the node name in the footer. The word is 0.85rem, which is a little smaller that the node name in the footer.
=> Issue 2329 - Adds the word testnet to the node access pop up

app/assets/locales/locale-de.json, app/assets/locales/locale-en.json, app/assets/locales/locale-es.json, app/assets/locales/locale-fr.json, app/assets/locales/locale-it.json, app/assets/locales/locale-ja.json, app/assets/locales/locale-ko.json, app/assets/locales/locale-tr.json, app/assets/locales/locale-zh.json
Closes #2369 
All were changed to the correct spelling except for RU. The word for "bridge" is in Russian.
=> Fixing issue #2369 - correct spelling of "bridge"

app/components/Dashboard/MarketsTable.jsx
The empty table TR doesn't show in the markets table when the table is empty
=> Empty table TR doesn't show when markets table is empty

app/components/Wallet/WalletUnlockModalLib.jsx
Closes #2301 
Remove redundant onclick handler on bin file loading.
=> Double bin file load fix

app/assets/locales/locale-en.json, app/assets/stylesheets/components/_exchange.scss, app/assets/stylesheets/themes/_theme-template.scss, app/components/Exchange/BuySell.jsx, app/components/Exchange/Exchange.jsx, app/components/Exchange/ScaledOrderTab.jsx, app/services/Math.js, app/services/Validation/Validation.js
Closes #2497 
I've removed Scaled Orders modal, added "tabs" for Buy/Sell blocks. Now we have "Limit" and "Scaled" tabs. 
How it looks:
=> #2497 scaled orders improvements

app/components/Exchange/ScaledOrderTab.jsx
#2599 
Changed the format of assets names on the Scaled Order form to match Limit order.
=> Fix asset name format on scaled order form.

app/assets/stylesheets/components/_exchange.scss, app/components/Exchange/Exchange.jsx
Closes #2561 
Adds missing padding to Buy/Sell order book SCSS which probably been lost during the addition of scaled orders on Buy/Sell form.
=> Issue 2561 - Add padding to order book header

app/components/Modal/DirectDebitModal.jsx
Closes #2560
As FIRST PERIOD of the new debit should be later than current date, I have disabled the date that earlier than 2 minutes after "now" in the DatePicker input (the default state of the form). It will avoid entering the wrong date and getting such error:
<h2> Testing</h2>
Tested in Chrome
<h2> User interface changes</h2>
=> Disable dates less then current in DatePicker to avoid error.

app/assets/locales/locale-en.json, app/assets/stylesheets/components/_exchange.scss, app/components/Exchange/MyOpenOrders.jsx
Closes #2317 
The following feature will enable the same feature on exchange as available in "Open Orders" today.
Each row has a checkbox that can be selected. It's also possible to use the "global" checkbox to toggle/un-toggle all checkboxes. Once at least one checkbox is checked, the cancel button is visible. This is today limited to one OP per order that you wish to cancel.
=> Issue 2317 - Multiple order cancelation on Exchange

app/assets/stylesheets/_shame.scss, app/assets/stylesheets/layout/_page_layout.scss, app/components/Blockchain/Asset.jsx, app/components/DepositWithdraw/OpenledgerGateway.jsx, app/components/DepositWithdraw/citadel/CitadelGateway.jsx, app/components/DepositWithdraw/gdex/GdexGateway.jsx, app/components/DepositWithdraw/openledger/OpenLedgerFiatDepositWithdrawal.jsx, app/components/DepositWithdraw/rudex/RuDexGateway.jsx, app/components/DepositWithdraw/xbtsx/XbtsxGateway.jsx, app/components/Layout/Footer.jsx, app/components/Modal/BrowserSupportModal.jsx, app/components/Modal/ReportModal.jsx, app/components/News.jsx, app/components/Settings/SettingsEntry.jsx, app/components/Utility/HelpContent.jsx
Closes #504 
class "external-link" (which adds icon after link) is added for all places, where external link is
lease make sure the following is done:
- [+] Check for unused code
- [+] No unrelated changes are included
- [+] None of the changed files are reformatting only
- [+] Code is self explanatory or documented
- [+] All written text is properly translated (english language)
_The branch has been tested on the following …
=> #504. Add icon for external links

app/assets/locales/locale-en.json, app/components/DepositWithdraw/DepositWithdrawAssetSelector.js
Closes #2597 
<h2>Notes</h2>
Currently the user receives a message that the list has no data when user has no withdrawable assets (ie, no assets that the gateways can handle).
The user should receive a clearer message that this is the case.
=> Issue 2597 - Default empty AssetSelector message

app/components/Modal/SendModal.jsx
Closes #801 
Re-enabled account images on Send Modal to increase security by popular demand and it's used elsewhere in the application.
=> Issue 801 - Re-enable Account Images on Send

app/assets/locales/locale-en.json, app/components/Blockchain/Asset.jsx
Closes #2570
- Add cumulative debt column to Collatoral Bids table 
- Add required translations for new column
- Add debt summation logic
=> Issue 2570 - Cumulative Debt Column

app/assets/locales/locale-de.json
Closes #2653 
Unescaped percentage sign crashed locale rendering. Required some time to locate the exact position for the issue.
=> Issue 2653 - Fix unescaped percentage sign in locale

app/components/Modal/WithdrawModalNew.jsx
Closes #2747 
Added function updateGatewayFee which called after changing gateway. But I see that gateway fee for RUDEX.EOS = 0 (check the screenshots please)
_Please …
=> #2747. update gateway fee after changing gateway

app/components/Account/AccountVesting.jsx, app/components/Modal/BorrowModal.jsx
Closes #2785 
When a margin position is updated without any debt/collateral change, but the user changes the TCR it will fail due to the core requires the debt/collateral to change.
This PR will make sure the collateral is changed with `1 * Collateral Asset Precision` if collateral amount and debt amount is 0 OR if user removes/adds TCR without changing debt/collateral.
=> Issue 2785 - Enable TCR Margin only Update

app/components/Account/AccountOrders.jsx
Closes #2780
Added saving of grouping policy in view settings
=> #2780 Added saving of assets grouping state in view settings

app/assets/locales/locale-de.json, app/assets/locales/locale-en.json, app/assets/locales/locale-es.json, app/assets/locales/locale-fr.json, app/assets/locales/locale-it.json, app/assets/locales/locale-ja.json, app/assets/locales/locale-ko.json, app/assets/locales/locale-ru.json, app/assets/locales/locale-tr.json, app/assets/locales/locale-zh.json, app/components/Blockchain/Asset.jsx, app/components/Utility/FormattedAsset.jsx
Closes #2778 
Closes #2777 
Moved unit info to header of the table in margins section of asset info.
Changed symbol and fixed columns resizing appropriately.
_Please provide …
=> #2777 #2778 Add asset to header and prevent margin position columns from resizing

app/assets/locales/locale-en.json, app/components/Exchange/MyOpenOrders.jsx
Closes #2825 
- Adds "Select all" specific tooltip
- Removed tooltip for each row
=> Issue 2825 - Exchange Cancel Order Translations

app/components/Blockchain/Asset.jsx
Closes #2839 
An invalid translation string was used, now fixed.
=> Issue 2830 - Asset Margin Table Translation error

app/components/Blockchain/operations/AccountUpdate.jsx
Closes #2834
When an account has a proposed Account Update operation it can sometimes break if the account proposing doesn't have a resolved owner object. Reason for this is not known, but this fixes the main cause of the white screen of death.
=> Issue 2834 - AccountUpdate Proposal Operation Fixes

app/components/Modal/WithdrawModalNew.jsx
Enables memo on Gateway Withdrawls
- Enable memo when backingAsset supports memos
Closes #2661
=> Issue 2661 - Enable Memo on Gateway Withdrawl

app/components/Account/AccountAssetUpdate.jsx, app/components/Account/AccountTreemap.jsx
Closes #2893, #2887 
- UpdateAsset requires asset name to be uppercase (#2893)
- AccountTreeMap with empty Balance (#2887)
=> Fixes various White screen issues

app/assets/locales/locale-de.json, app/assets/locales/locale-en.json, app/assets/locales/locale-es.json, app/assets/locales/locale-fr.json, app/assets/locales/locale-it.json, app/assets/locales/locale-ja.json, app/assets/locales/locale-ko.json, app/assets/locales/locale-ru.json, app/assets/locales/locale-tr.json, app/assets/locales/locale-zh.json, app/components/Exchange/MarketHistory.jsx
Closes #2885 
Empty order book should not state "No open orders".
Replaced to state "No order history".
=> Issue 2885 - Invalid translation for missing order history

app/components/Blockchain/Asset.jsx, app/components/Blockchain/AssetResolvePrediction.jsx
Closes #2890 
Asset action crash
- Load resolve prediction only when asset is prediction bitasset.
=> Issue 2890 - Non Prediction Asset fixes

app/components/Exchange/Exchange.jsx
This PR will add a small fix to sort the Panel tabs by key to make it sort "Market History" before "My History".
The only real change made is to line 2982
https://github.com/bitshares/bitshares-ui/blob/0708643ddfb555e0238cf01bcd986dbdd4116ca6/app/components/Exchange/Exchange.jsx#L2927-L2930
Closes #2858
=> Issue 2858 - Exchange Panel Tabs order

app/components/Account/RecentTransactions.jsx, app/components/Utility/PendingBlock.jsx
Closes #2838 
Added new component which updates when last_irreversible_block_num is changed.
=> #2838. Blocks freeze on transaction history tab

app/assets/stylesheets/themes/_theme-template.scss, app/components/Blockchain/Asset.jsx
This PR updates the Asset Feed Table with more data while making it sortable. To make it more informative to investors that wish to monitor feed producers.
```
+ Sort tables by feeder, feed_price or feed_time
+ View offset % from median price
```
Closes #2947
=> Issue 2947 - Asset Feed Table updates

app/components/Modal/HtlcModal.jsx, app/components/Showcases/Htlc.jsx
Closes #2874
There was an error, when modal was not updating expiration date after syncOperation .
Noticed that after fix 'one day' period was still selected - added period unset on operation sync.
_Delete this section if there weren't any UI changes. Please make sure you tested …
=> 139 htlc expires mismatch

app/components/Exchange/MarketHistory.jsx, app/components/Exchange/View/MarketHistoryView.jsx
This PR fixes an issue on development branch that creates a infinite loop when a component tries to reference a functional component, and fails.
It also adds a key ID to the `<MarketHistoryViewRow />` component, reducing an error message for missing key.
Closes #2963
=> Issue 2963 - Market history fix

app/assets/stylesheets/components/_exchange.scss, app/components/Exchange/OrderBook.jsx
Closes #2902 
add possibility to change asset in total column
=> #2902. different asset for total column (Order book)

app/assets/stylesheets/components/_asset.scss, app/assets/stylesheets/themes/_theme-template.scss, app/components/Blockchain/Asset.jsx
Closes #2930
https://github.com/blockchainprojects/bitshares-ui/pull/157
- extended the collapsable approach to asset actions
- played around with responsiveness on asset info
- removed unused stylings
<h2>Bounty</h2>
Hours spent: 9
Bounty request: 3.5
=> #2930 make collateral positions easier accessable

app/stores/AccountStore.js
This PR changes the stored referral slightly.
Previously any stored referral where removed on revisit, or updated with a new one. This is not a good way to promote referral handling. 
```
* Update referral account when supplied
* Never forget last used referral
```
Closes #2555
=> Issue 2555 - Referral updates

app/assets/locales/locale-en.json, app/components/Account/AccountSelector.jsx, app/components/Modal/SendModal.jsx, app/components/Modal/SetDefaultFeeAssetModal.jsx, app/components/Settings/FeeAssetSettings.jsx, app/components/Utility/AmountSelectorStyleGuide.jsx, app/components/Utility/AssetSelect.jsx, app/components/Utility/FeeAssetSelector.jsx, app/lib/common/trxHelper.js
This PR closes #2756 (overrides previous PR)
This PR contains a significant larger change to the structure, most notable is the usage of `fetchChainObjects`, recurring quering even if account does not exists and a few code cleanups.
Workings are as follows
- Component mounts and adds favorites and contacts to the searchResult list through `_addToSearch`.
- User types an input and it gets added to teh searchResults list, which will hold `_fetchAccounts` for 250ms to prevent unnecessary queries while the user still inputs data.
- `_fetchAccounts` will query all accounts still missing and process them. Any remaining which have failed (produced no return due to slow node non existing account) will be queried again, up to `max_fails`.
- While query is running, a spinner will be visible at the …
=> 2756 - Account Selecotor Updates

app/components/Layout/Header.jsx, deploy.sh
Closes #2860
Add auto close of account notification when user open menu/account management dropdown or open account unlock modal
Before: 
After:
=> 2860 account switch tooltip should not hide user menu

app/components/Utility/BindToChainState.jsx
Closes #2498 
Added error message when required prop is missing
=> #2498. BindToChainState rendering when required prop is missing

app/components/Account/RecentTransactions.jsx, app/services/AccountHistoryExporter.js
This PR fixes the export of account CSV issue.
When an ES node sends data back, an item can sometimes have a `{ data: null }` value, resulting in an error creating the exported file.
=> [1] Fix Export History

app/api/apiConfig.js
It's stated clearly in wechat that they'll no longer maintain an API node.
=> Remove xman's API node

app/actions/LogsActions.js, app/components/Blockchain/Asset.jsx
for #3053
this is due to usage of chainstore.get method for lazy loading, which is unsuitable if not properly subscribed (should use fetch)
=> fix .get on undefined when loading asset directly

app/stores/MarketsStore.js
Markets without Asks/Bids would crash DepthChart rendering
Example: SGD_BTS
If flat_bids/flat_asks is empty, length would still return true as an empty array. Check if array is larger than 0 instead.
=> Depth Chart Fix

app/components/Exchange/MyMarkets.jsx
This would eliminate the behavior of reference UI pointing at defunct OPEN markets and make the default behavior gateway UIA and smartcoin MPA agnostic by pointing towards all Bitcoin markets.
I also suggest it be implemented in conjunction with:
`Use BTS as find market basic pair by froooze · Pull Request #3191`
So that then BTS is the default primary search token and all Bitcoin markets which pair to BTS are shown by default.
=> Use BTC as default find-market search instead of OPEN

app/components/DepositWithdraw/blocktrades/BlockTradesBridgeDepositRequest.jsx, app/components/DepositWithdraw/blocktrades/WithdrawModalBlocktrades.jsx, app/lib/common/gatewayMethods.js
Blocktrades bridge has functionality in wich users can do withdrawals. Memo information is now based on data which are getting from new mapping API call.
There were not changes in UI.
=> Make bridge withdrawals based on mapping data

app/components/Account/FeePoolOperation.jsx
+ fix bug in claim asset fees
1. Go to ANY asset page: 
https://wallet.bitshares.org/#/asset/CNY (example)
2. Click to TAB "ASSET ACTIONS"
3. Click to "CLAIM ASSET FEES"
4. Click "AVAILABLE: 3,418.3899 bitCNY"
And you will see that nothing is happening - this amount is not substituted in the appropriate field for editing and generating a transaction.
and the "Claim fees" button remains inactive.
=> fix bug in claim asset fees (feePoolOperations)

app/components/Wallet/BackupBrainkey.jsx, app/components/Wallet/WalletChangePassword.jsx
**fix 2 not working buttons:**
- show the brain key
- confirm the password (in the password change section in options)
1. Go to: https://wallet.bitshares.org/#/settings/password
and try entering the current password
the button does not work there.
but the event on the ENTER key works
need to create a bind on the button.
2. Go to: https://wallet.bitshares.org/#/settings/backup
choose:
"Create brainkey backup"
and try entering the current password for show brainkey
the button does not work there.
but the event on the ENTER key works
need to create a bind on the button.
also a small fix with a pop-up notification.
=> fix 2 not working buttons (for show brainkey and change password)

app/api/apiConfig.js
Remove:
* `api-ru.bts.blckchnd.com` : domain name doesn't resolve. Asked the maintainer, no response so far. BTW found a new API node wss://node.market.rudex.org on rudex.org .
* `dexnode.net` : domain name doesn't resolve. The maintainer (Sahkan) said he didn't decide whether to fix it.
* `kc-us-dex.xeldal.com` : refuses connection. Unable to contact the maintainer.
* `bit.btsabc.org` : connection time out. The maintainer confirmed the node had been shut down.
Add:
* `api.cnvote.vip:888`
* `fujian.cnvote.vip:81`
=> Update API nodes

app/api/apiConfig.js
The citadel.li node has been out of sync for months.
The api.bts.ai node is now temporarily closed.
=> Comment out API nodes which are temporarily down

app/api/apiConfig.js
One node is being shut down, the other has been down for a long time.
=> Remove the New Jersey nodes

app/components/Account/AccountSelector.jsx, app/components/Modal/SendModal.jsx
Workaround for #3343
Add a new property `includeMyActiveAccounts` to Account Selector, enabled by default, disabled in Send Modal.
BTW updated some checks so that checking for scammers has higher priority.
The screenshot below was for reproducing a …
=> Hide own accounts from to field in send modal

charting_library/install-charting-library.js
In one run of the CI process, the `npm ci` step went through but  `npm build` failed. Actually `npm ci` should fail.
More info: https://github.com/abitmore/bitshares-ui/pull/6/checks?check_run_id=1954163481 or https://ci.appveyor.com/project/svk31/bitshares-ui/builds/37891710
(Note: the charting lib downloading issue has been fixed, thus unable to reproduce the issue as is.  https://github.com/bitshares/bitshares-ui/pull/3342 reproduces it.)
```
Run npm ci
...
> BitShares2-light@5.0.20210216 install-charting-library /home/runner/work/bitshares-ui/bitshares-ui
> node ./charting_library/install-charting-library.js && npm run compile-tv-css
Failed to download charting_library archive
{ Error: connect ETIMEDOUT 149.28.203.167:443
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14) …
```
=> Rethrow error when failed to download charting lib

app/components/Account/CreateAccountPassword.jsx, app/components/Wallet/WalletUnlockModalLib.jsx
issue 1:
issue 2:
> Warning: Use the `defaultValue` or `value` props instead of setting children on <textarea>.
in textarea (created by CreateAccountPassword)
=> Fix #3264, get rid of warnings

.github/workflows/npm-build-and-deploy-develop.yml
Fixes the deposit-withdraw page missing issue when doing auto-deployment via Github Actions (https://github.com/bitshares/bitshares-ui/issues/3302#issuecomment-766249950).
Related code:
https://github.com/bitshares/bitshares-ui/blob/df6d96e0d6b38c1c491d72d05ed0575e603e2cf2/build.sh#L14-L18
https://github.com/bitshares/bitshares-ui/blob/df6d96e0d6b38c1c491d72d05ed0575e603e2cf2/package.json#L41-L43
https://github.com/bitshares/bitshares-ui/blob/df6d96e0d6b38c1c491d72d05ed0575e603e2cf2/webpack.config.js#L208-L235
=> Run build-hash instead of build in Github Actions

app/assets/stylesheets/vendors/foundation/_global.scss
=> Fixing header's username not fully appearing

app/api/apiConfig.js
The node has switched to another chain. `chain_id [cd931cb96d657ff0ef0226f7ae9d25175b3cc96a84490a674ed36170830324e7]`
=> Remove an API node

.github/workflows/npm-build-and-deploy-develop.yml, appveyor.yml
<h2>fix appveyor and action bug</h2>
Fix 'appveyor' and 'action' build failures due to network issues.
=> fix appveyor and action bug

.github/workflows/build-release-binaries.yml
<h2>Update current travis and appveyor to GitHub actions</h2>
About the modification of #3414 and #3302
This action will automatically generate the following effects when triggered:
=> upgrade travis and appveyor to github action

app/components/Modal/DepositModal.jsx
In case platform user owns multiple users and wants to deposit to thus different users; they will need to clear the browser cache every time they want to use different user for deposit modal API data.
=> Destroy deposit modal cache upon closing it

app/help/en/components/BorrowModal.md
=> BorrowModal.md

app/assets/locales/locale-en.json, app/assets/locales/locale-zh.json, app/components/Blockchain/OperationAnt.js
Added credit offer and liquidity operation history analysis. #3408 
Among them, the language support only includes Chinese and English.
=> Added credit offer and liquidity operation history analysis.

app/components/DepositWithdraw/gdex/GdexGateway.jsx
I got info that tickets are not being processed as before, so showing the link on UI does not help. In this PR I commented it out so far, probably remove it some day in the future.
The official support is on WeChat (Weixin), but it is hard to provide a link in the UI.
Don't know if the QQ group still works since I can no longer login to QQ due to KYC issues.
For the Telegram group, at least other community members (including me) can forward messages.
=> Comment out the link to the GDEX ticketing system

app/components/Account/CreditOffer/CreditOfferPage.jsx
<h2>Fix inaccurate floating point numbers used in credit offers</h2>
Closes #3487
=> Fix inaccurate floating point numbers used in credit offers #3487

app/actions/CreditOfferActions.js, app/assets/locales/locale-en.json, app/assets/locales/locale-zh.json, app/components/Account/CreditOffer/CreditOfferList.jsx, app/components/Account/CreditOffer/CreditOfferPage.jsx
<h2>Fix Credit offer repayment period 'No limit'</h2>
Closes #3490
=> fix #3490, Credit offer repayment period 'No limit'

app/actions/MarketsActions.js, app/components/Exchange/MyOpenOrders.jsx, app/lib/common/account_utils.js
<h2>Handle issues mentioned in #3486</h2>
Closes #3486
=> Fix #3486 "Order cancellation fee error"

app/lib/common/trxHelper.js
<h2>Fix UI estimated fee error</h2>
Closes #3505
=> UI estimated fee error #3505

app/components/Layout/MenuDataStructure.js
It was removed here: https://github.com/bitshares/bitshares-ui/pull/3462/commits/f67d1cd0d0a14e4225843b3eaa9399054a375223#diff-d63a7b057087487c08e48334a07bc30032568fdf51b3b0f0dda62de0c57ccdfbL226
=> Add credit offers to top menu

app/components/Account/CreditOffer/CreditOfferAccountPage.jsx
It caused the error:
ReferenceError: CreditOfferList is not defined
at Un.render (account.cf361fa9202f7a8d1105.js:1:319940)
at Ra (vendor.049af5c1d008aea05c6b.js:2:3628660)
at za (vendor.049af5c1d008aea05c6b.js:2:3628455)
at bs (vendor.049af5c1d008aea05c6b.js:2:3663936)
at hc (vendor.049af5c1d008aea05c6b.js:2:3655411)
at fc (vendor.049af5c1d008aea05c6b.js:2:3655336)
at rc (vendor.049af5c1d008aea05c6b.js:2:3652366)
at vendor.049af5c1d008aea05c6b.js:2:3604139
at t.unstable_runWithPriority (vendor.049af5c1d008aea05c6b.js:2:4148188)
at Ko (vendor.049af5c1d008aea05c6b.js:2:3603848)
=> This was dropped due to a mistake

app/assets/stylesheets/components/_exchange.scss, app/components/Exchange/OrderBook.jsx
https://github.com/bitshares/bitshares-ui/pull/3522 was closed, but the change was included in #3378.
This PR also changes the table header to right-aligned. 
Before:
After: …
=> Right align numbers in the order table

app/assets/locales/locale-en.json
Discussion was addressed at DEV group and concluded that *Fee Schedule* might be misleading and might get understood as *reoccurring fees* or fees related to time.
=> Changing *Fee Schedule* to *Fees*

.github/workflows/build-release-binaries.yml
Closes #3535.
Replace incorrect use of `hashFiles()` function with shell commands.
This is for `master` branch only.
=> Fix binary file hash calculation

app/api/apiConfig.js
This should fix deposit/withdrawal.
BTW I guess the legacy deposit/withdrawal page for GDEX no longer works. Not tested.
=> Update base URL of GDEX gateway API

app/components/Modal/PoolExchangeModal.jsx
=> Fixing Float-to-Integer producing too many digits

app/components/Account/CreditOffer/CreditDebtList.jsx
User had reported the below error while submitting *repay credit deal operation*:
A core check is rejecting *9* as the credit_fee amount of the operation; it was found that the determination of credit_fee amount is coming through the code equation (fRate * debtAmount * rate); it was solved by rounded up result using Math.ceil()
Testing credits to @thontron
=> Fixing Bug with Credit Fee Amount in Credit Offer

app/components/Modal/PoolStakeModal.jsx
=> LP staking (A determine B and B determine A)

app/api/ApplicationApi.js
User had reported that *feeAsset* is turning into *liquidity pool asset* while attempting to perform withdraw from a liquidity pool, seems bug is effecting objects.feeAsset.get("id") default object at liquidity pools withdraw *modal* which should show feeAsset as core asset.
Before fixing the bug:
After fixing the bug:
=> Adding support for *default fee paying asset* in ApplicationApi

app/components/Exchange/PriceStatWithLabel.jsx
If you change the ticker in ExchangeHeader - the volume ticker doesn't get changed in case `previous market volume === new market volume`. This PR fixes a logic of `shouldComponentUpdate`
=> Update component if ticker changed

app/App.jsx
In that check, a variable `myActiveAccounts` is an immutable Set instead of an array. So the proper way to check it's size is a `.size`.
This bug may lead to improper logic of Gateways coins fetch, that are available to deposit/withdraw
=> Fix ActiveAccounts check

app/api/ApplicationApi.js
For `withdraw_permission_claim_operation`, it is the claimer who pays the fee.
Also fixes `vesting_balance_create_operation`, `ticket_create_operation` and liquidity pool operations.
=> Fix fee payers in ApplicationApi.js

app/components/DepositWithdraw/DepositWithdrawAssetSelector.js
When a user tries to process a search though assets in withdraw modal the component crashes. 
(I'm trying to type anything in the input and filtering doesn't work and input crashes)
=> Fix withdraw modal search though assets

app/branding.js, app/components/News.jsx, package.json, yarn.lock
**Issue** #3580 
- Replaced steemit lib with hive
- Use `bitshares` tag to fetch hives' news
=> #3580 Replace steemit news by hive and use bitshares tag

app/assets/locales/locale-en.json, app/components/Account/CreditOffer/CreditDebtList.jsx, app/components/Account/CreditOffer/EditModal.jsx
**Issue** #3567
- I have renamed the title of Amount for edit dialog. Now it is a "Currently Available Balance" (to avoid misunderstanding)
- Fixed the balance check to avoid the fake error which blocked the edit
- Fixed the delta amount which sends to the blockchain 
- Added the "Total to Repay" for Repay window (I had a misunderstanding and insufficient balance error, so I decided to display for a user the sum that gonna be withdrawn from his account (credit fee + repay amount)
Closes #3567
=> #3567 credit offers edit

app/components/Exchange/DepthHighChart.jsx, app/components/Exchange/Exchange.jsx, app/lib/common/numberExplonentConversion.js
**Issue** #3525 
- Fixed exponential numbers for Exchange
- Also fixed for Market Depth
**How to test?**
- Go to Exchange
- Click on BTS
- Find xbtsx.btc 
Closes #3525
=> #3525 Fix exponential numbers on Exchange & MarketDepth

app/assets/stylesheets/base/_fonts.scss
**Issue** #3352 
Fixed by proper css styling
=> #3352 Fix css styles for json-inspector

app/assets/locales/locale-en.json, app/components/Account/CreditOffer/CreditOfferPage.jsx
=> #3576 Inform user about borrowing assets with override_authority setting

.github/workflows/build-release-binaries.yml
Closes #3535 
Closes #3585
Closes #3632 
Changes:
* Install `coreutils` which contains the `sha256sum` command for `macOS`
* replace `::set-output` with `>> $GITHUB_OUTPUT`
This is for `master` branch only.
=> Fix release binary file hash calculation

app/components/Exchange/OrderBook.jsx
For better view when there are orders with extremely large amounts on the order book (I still don't think the user experience after this change is good enough).
Follow-up of https://github.com/bitshares/bitshares-ui/pull/3572.
Before the change:
After the change:
=> Use totalForSale to calculate market depth displayed in order book

app/components/Modal/View/BorrowModalView.jsx
Asset `CNY16` has an `ICR` of `32` and an `MCR` of `1.003`, so users can't adjust debt positions with the current code.
=> Increase maximum collateral ratio in BorrowModalView

.github/workflows/npm-build-and-deploy.yml
Use 'v4' tag which points to the latest and secure version.
=> Update download-artifact to v4

app/api/apiConfig.js, app/lib/common/gateways.js
We're moving the API to the shorter domain pirate.cash from piratecash.net. Currently, the old domain has a proxy for /dexapi for backward compatibility and all other requests are redirected to the p.cash site. The pirate.cash domain will continue to support our DEX API.
=> Update endpoint and wallet URL for piratecash gateway

app/actions/WalletActions.js, app/components/Account/AccountVesting.jsx
Support claiming vesting balances with linear vesting policy.
For vesting balances with linear vesting policy, on the vesting balances page,
* fix days left of vesting period, and
* show percentage available to claim, and
* fix the amount to claim in the dialog when clicked the "claim now" button.
See screenshots below.
Before the change:
After the change:
=> Fix linear vesting policy
