bitshares/bitshares-ui

README.md

Badge with link to official slack

---

web/app/assets/asset-symbols/symbols.js

This asset is going to be redeemable for one pound of xylitol produced by HempSweet company

add hempsweet UIA symbol

---

web/app/assets/locales/locale-tr.json

"Deposit & Withdraw" title under the tab Deposit/Withdraw has no key. It should be added too.

Add more translation

---

help/en/dex/introduction.md
web/app/assets/stylesheets/components/_all.scss
web/app/assets/stylesheets/components/_help.scss

- Set max-width of text column
- Format tables
- Other minor changes
On the side note: some sections (i.e. backups, membership) are outdated.

An attempt to improve Help content readability.

---

help/en/components/AccountVoting.md
help/en/components/AccountVotingProxy.md
web/app/assets/locales/locale-en.json
web/app/components/Account/AccountVotingProxy.jsx

Proposed changes to Voting Proxy page based upon issue #138

#138 Removed Goto button on proxy page, Added verbiage to proxy page

---

web/app/assets/locales/locale-en.json

Bitshares -> BitShares

---

README.md

Fix broken telegram chat room link

---

web/app/components/Account/AccountMembership.jsx

This PR resolves https://github.com/bitshares/bitshares-ui/issues/171

Update membership link to include slash as per issue comments

---

README.md
electron/package.json

- Update build instructions for more clarity
- Added optional dependency as dependency for electron to match instructions

252 - OSX build with new bitshares updates

---

web/app/components/Account/AccountAssetCreate.jsx

RP for #265 
fix the cursor jump to the end issue when update the SYMBOL input

Resolve Issue #265

---

web/app/components/Layout/Header.jsx

Fix issue #211 
Clicking EXCHANGE defaults to "bitUSD : BTS" if Already in Exchange

Fix issue #211

---

web/app/components/Exchange/OrderBook.jsx

RP for #237 
In horizontal mode when order data loaded should calculate the scroll size

Resolve Issue #237

---

web/app/assets/stylesheets/components/_help.scss
web/app/assets/stylesheets/layout/_page_layout.scss
web/app/assets/stylesheets/themes/_theme-template.scss
web/app/components/Account/AccountAssetCreate.jsx
web/app/components/Account/AccountAssetUpdate.jsx
web/app/components/Account/AccountOverview.jsx
web/app/components/Account/AccountPermissions.jsx
web/app/components/Account/AccountPermissionsMigrate.jsx
web/app/components/Account/AccountSelector.jsx
web/app/components/Account/AccountVoting.jsx
web/app/components/Account/AccountVotingProxy.jsx
web/app/components/Utility/HelpContent.jsx

Reverts bitshares/bitshares-ui#273

Revert "Fix a bunch of UI padding issues"

---

web/app/assets/stylesheets/components/_dashboard.scss
web/app/components/Account/AccountAssetCreate.jsx
web/app/components/Dashboard/SimpleDepositWithdraw.jsx
web/app/components/DepositWithdraw/blocktrades/WithdrawModalBlocktrades.jsx
web/app/components/Exchange/BuySell.jsx
web/app/components/Exchange/Exchange.jsx
web/app/components/Transfer/Transfer.jsx
web/app/components/Utility/AmountSelector.jsx
web/app/components/Utility/FormattedFee.jsx
web/lib/common/MarketClasses.js
web/lib/common/account_utils.js
web/lib/common/trxHelper.js
web/lib/common/utils.js

Fixes issue #85 and should help with preventing the issue in #221, #213 , #183

Add memo fee calculation to multiple components

---

web/app/components/Exchange/Exchange.jsx
web/app/components/Exchange/PriceChartD3.jsx

RP for #275 
`const minChartHeight = 300` is config for the chart min height . 
if use input number is less than `minChartHeight` , the chart still height as `minChartHeight`

Fix issue #275

---

web/app/assets/index-dev.html
web/app/assets/index-electron.html
web/app/assets/index.html

RP for #305 
I found the doc [https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors) ,  `frame-ancestors` not support meta element , So i remove it .

Fix issue #305

---

web/app/components/Exchange/MyMarkets.jsx

Issue #291: Added maxLength Property To Asset Selector and Filter Input Fields.

---

web/app/components/Settings/AccessSettings.jsx

Resolves notes left by @wmbutler in [issue 49](https://github.com/bitshares/bitshares-ui/issues/49):
- Nodes sorted by latency
- Down nodes appear last
- Defaults cannot be removed

Issue 49 - Resolve bullet points from bill

---

.gitignore
web/app/components/Settings/AccessSettings.jsx

Should resolve issue in electron where Add Node button was sending user to home page:

Resolve linking issue in electron

---

web/app/assets/stylesheets/layout/_page_layout.scss
web/app/assets/stylesheets/utils/_utils.scss
web/app/components/Layout/Header.jsx

Hi, I just started to get acquainted with the source, so it is important to me to start with clear console.
Here is fix for "every page warning" (<td in <a)

Fix warning in header (td in a)

---

web/app/components/Modal/BorrowModal.jsx

Fix issue #334

---

app/components/Exchange/MarketHistory.jsx

Fix #385 make height is same with open orders

---

app/assets/colors.js
app/components/Exchange/PriceChartD3.jsx

Using yellow for zero size candles, only for dark theme.

Fixed #392

---

app/assets/colors.js
app/components/Exchange/PriceChartD3.jsx

Reverts bitshares/bitshares-ui#401

Revert "Fixed #392"

---

app/App.jsx
app/assets/locales/locale-en.json
app/components/Layout/Incognito.jsx
app/components/LoginSelector.jsx
app/lib/feature_detect/browser.js
app/lib/feature_detect/incognito.js
app/lib/feature_detect/index.js
app/routerTransition.js

Resolves [issue 364](https://github.com/bitshares/bitshares-ui/issues/364). 
This PR implements a blocker for Incognito mode. It also adds some centralized detection code for browsers & incognito.

Issue 364 - Present an error message that disallows the use of Incognito with the BTS wallet

---

app/lib/common/utils.js

Added "RUDEX." to known prefixes
RuDEX gateway works on rudex.org right now. But we will create pull request soon to upstream too. Testing gateway api and ui.

Added RUDEX to known prefixes

---

app/assets/stylesheets/components/_exchange.scss
app/components/Exchange/MarketHistory.jsx
app/components/Exchange/MyOpenOrders.jsx
app/components/Exchange/OrderBook.jsx

Fix #429  right justify table headers

---

package.json

[417] update electron version to fix missing extension issue

---

app/assets/locales/locale-cn.json
app/assets/locales/locale-en.json
app/components/Modal/QrcodeModal.jsx
app/components/PrivateKeyView.jsx
package.json

Add an optional encrypted qr code for the private key.
The solution is [issues #444 ](https://github.com/bitshares/bitshares-ui/issues/444)

Add an optional encrypted qr code for the private key

---

app/actions/GatewayActions.js
app/assets/locales/locale-en.json
app/components/Account/AccountDepositWithdraw.jsx
app/components/Account/AccountOverview.jsx
app/components/Account/AccountPage.jsx
app/components/Dashboard/SimpleDepositBlocktradesBridge.jsx
app/components/Dashboard/SimpleDepositWithdraw.jsx
app/stores/GatewayStore.js

This shows error message if more than 10s go by without a response. To test, you can change your hosts file so these requests will time out, i.e.
```
10.10.10.10 openledger.info ol-api1.openledger.info
10.10.10.10 rudex.org gateway.rudex.org
```
Resolves issue #547

iss-547: Show unavailable messages for openledger and rudex if they time out

---

app/components/Exchange/Exchange.jsx

Round up `for_sale` and down `to_receive`, #562

---

app/components/Exchange/ExchangeInput.jsx

Make sure exchange input only allows numbers, does not allow negative values, only allows a single decimal, cannot be changed with mouse wheel
Resolves #507

Iss 507 - Exchange value entry

---

app/assets/locales/locale-en.json

Fixes https://github.com/bitshares/bitshares-ui/issues/625

Capitalization typo in menu

---

app/components/Dashboard/Dashboard.jsx

Fix Issue 645

---

app/components/Layout/Footer.jsx

Fixes issue #633 
Take the user to the access settings page when clicking the sync status

Fix Issue 633

---

app/components/Blockchain/Asset.jsx

Fix for Issue #627 
"Published" time stamp not honoring UTC offset in "Price Feed Data" Table

Fix Issue #627

---

app/assets/stylesheets/vendors/_foundation_overrides.scss

Fix for Issue #598 
Collateral breaks layout due to an error in CSS error layout

Fix Issue 598

---

app/components/Layout/Footer.jsx

Fixes Issued #739 
If no latency of the current node URI is available, display "-" instead of _Undefined_

Fix Issue #739 - Undefined Latency

---

app/components/Modal/BorrowModal.jsx

Fixes Issue #719 
- Solves issues with assets valued less than 0.00 not displaying their value

Fix Issue #719 - Decimal Placement for Assets in Borrow Modal

---

app/assets/stylesheets/components/_dashboard.scss
app/components/Dashboard/SimpleDepositBlocktradesBridge.jsx

Last few changes to the Modal to correct the layout as well as the input of numbers not working working correctly.

Fix Issue #651 - Fixing Modal Layout

---

app/App.jsx
app/components/Layout/Header.jsx

My Bitshares Account: **fundon**.
Fixed #715 dropdown menu cant scroll and supproted resize window height.
By the way, If I have time, I will continuous improve UI.

fix: dropdown menu cant scroll, #715

---

app/assets/locales/locale-en.json
app/assets/stylesheets/components/_forms.scss
app/components/Account/CreateAccount.jsx
app/components/Wallet/Backup.jsx

Fix for Issue #738 
- Applies navigational back buttons for the Restore and Advanced wallet pages
- Complies with the Send Modal for _forms.scss

Fix Issue #738 - Apply Back Buttons

---

app/components/Dashboard/DashboardList.jsx
app/components/Explorer/Accounts.jsx

Fixes Issue #781 
- Dashboard can remove contact
- Explorer/Accounts can add and remove accounts on search

Fix Issue #781 - Add/Remove Contacts

---

app/components/DepositWithdraw/blocktrades/WithdrawModalBlocktrades.jsx

fixed usage of undefined property which makes withdrawal popup to do nothing.
Also, there was similar problem when a user tries to withdraw coins which he doesn't hold that i've also fixed

#765 fixed usage of some undefined properties on withdrawal

---

app/assets/locales/locale-en.json

changed value of label "reset" in en language resource

Fixed: Cancel button doesn't work when creating assets #799

---

app/components/Account/MarginPositions.jsx

fixed commits message to contain issue id

Added gold and silver to margin positions #833

---

app/components/Dashboard/Dashboard.jsx
app/components/Dashboard/DashboardList.jsx
app/components/Layout/Header.jsx

Fixes Issue #807 
- Make sure that accounts tab is active on menu selection
- Enable pointer on account name

Fix Issue #807 - Accounts Tab Settings

---

app/components/Account/AccountSignedMessages.jsx

...by removing the line breaks caused by multiple `split`s.
A working wallet with this PR is running at https://b.mrx.im/.

Fix issue #861 - Correctly parse signed message

---

app/components/News.jsx

<s>Working version is running on https://b.mrx.im/news.</s>
Maintaining code containing modifications from two branches is kinda troublesome, and by mistake I've spammed the original issue twice already. I'm dedicating my web wallet to the translation branch for a while. Sorry for the inconvenience.

Fix incorrect news publish date, part of #887

---

app/components/Explorer/Witnesses.jsx
app/stores/MarketsStore.js

Fix Issue #919

---

app/assets/stylesheets/components/_header.scss
app/assets/stylesheets/themes/_theme-template.scss
app/components/Icon/Icon.jsx
app/components/Icon/hamburger-x.svg
app/components/Icon/hamburger.svg
app/components/Layout/Header.jsx

Changes triangle to burger in preparation for hierarchical right menu.
Fixes: Issue #929 .

Changes Caret To Burger

---

app/assets/stylesheets/base/_fonts.scss
app/assets/stylesheets/components/_blocktrades.scss
app/assets/stylesheets/themes/_theme-template.scss
app/components/DepositWithdraw/blocktrades/BlockTradesBridgeDepositRequest.jsx

Changes are related to Blocktrades Bridge section. Announcements helpful for users are displayed on page.

Announcements

---

app/assets/stylesheets/themes/_theme-template.scss

See issue for preview.
This fixes #949

Fix #949: Change icon color to fit the theme

---

app/api/apiConfig.js

Added new full API node provided by blckchnd witness

Add new API server

---

app/components/Modal/BorrowModal.jsx

"Maximize Collateral" will need to be translated.  I didn't add it to the translation matrix because I'm not entirely sure how that's set up and didn't want to inadvertently cause breakage for someone in a different locale.
- Fixes #901

Add "Maximize Collateral" button to Borrow Modal.

---

app/api/apiConfig.js

Added city name where node is located

Updated blckchnd api node info

---

app/assets/stylesheets/themes/_theme-template.scss
app/components/Layout/Header.jsx

Fix #991: move the lock button out of the menu area

---

app/components/Account/AccountOverview.jsx
app/components/Account/MarginPositions.jsx

Adds to the margin positions screen the amount of debt assets which the account holds in a balance column.

Show Balance on Margin Positions Tab #994 

---

app/components/Blockchain/Fees.jsx

Fix #996: change LTM fee rate for asset creation

---

app/components/Account/AccountOverview.jsx
app/components/Dashboard/SimpleDepositBlocktradesBridge.jsx

Fixes Issue #1001
- Gateways not yet supported by the Deposit Modal (Beta) should not be presented by a deposit icon.
- Minor fixes to Send Modal

Fix Issue #1001

---

app/routerTransition.js

See https://github.com/bitshares/bitshares-ui/issues/937#issuecomment-358031776 for notes.
This fixes #937

Fix #937: Infinite loop on start without network connection

---

app/components/Account/MarginPositions.jsx

Fixed issue #1047

---

app/assets/locales/locale-en.json
app/assets/stylesheets/components/_account.scss
app/components/Account/AccountVoting.jsx
app/components/Account/WorkerApproval.jsx

Added worker ID to voting area

---

app/components/Exchange/Exchange.jsx
app/components/Exchange/MyOpenOrders.jsx
app/components/Exchange/OpenSettleOrders.jsx

Fix Issue #744 - New Market Settlement Tab Style

---

app/assets/locales/locale-en.json
app/components/Blockchain/Asset.jsx

Added a global settlement price to the assets page.

---

app/assets/locales/locale-de.json

Fixed some typos and errors. Ask a German guy for verification.

Typos and errors fixed in the German locale

---

app/components/Account/AccountVoting.jsx

Addresses issue #1101 
**Before**
**After**

Added colspan to fix daily budget on active worker proposals

---

app/assets/locales/locale-de.json

https://www.duden.de/rechtschreibung/Komitee, missing "delete_confirm_line1" from engl. json

Fixed more typos and mistakes

---

app/assets/locales/locale-en.json
app/components/Exchange/DepthHighChart.jsx
app/components/Exchange/Exchange.jsx
app/components/Exchange/ExchangeHeader.jsx

Fixes issue #1043 
Markets Header
- Add correct settlement price (with offset)
- Add Feed Price
Depth Chart
- Change Settlement to Feed Price

Fix Issue 1043 - Fixes Settlement / Feed Price

---

app/assets/index.html

Remove tracking code. #1118

---

app/assets/index-electron.html

Also remove js tracking code from index-electron.html per #1118 (#1121)

Remove tracking code per #1118 (#1121)

---

app/components/Account/AccountOverview.jsx
app/components/Icon/Icon.jsx
app/components/Icon/PulseIcon.js
app/components/Icon/dollar-green.svg

**# Fixes Issues #359** 
- Pulses buy button green when BTS is below 1

359: Added green pulsing buy button when BTS is under 1 BTS

---

app/components/Utility/TypeAhead.js

- Hides and shows menu and creates a more uniform look

993: Update UI style and UX of TypeAhead to show/hide on click

---

app/components/Utility/EquivalentPrice.jsx

Fix Issue #1195 - Asset Equivalent Price Issue

---

app/components/Exchange/OrderBook.jsx

- Allows autoscroll toggle to work and keeps scroll in correct place based on autoscroll toggle

1133 order book shifts

---

app/routerTransition.js

Fix error in url assignment

---

app/components/Blockchain/Asset.jsx
app/components/Utility/FormattedTime.jsx

- Changed <a> tag to <Link> to prevent app reload and keep window history
- Commented out unnecessary debug output

Fix Issue #1245 - Market Link and Debug output

---

app/components/InitError.jsx

Allow wallet to connect to hidden nodes when none other are available

---

app/assets/stylesheets/themes/_dark-theme.scss
app/assets/stylesheets/themes/_light-theme.scss

Fixed colours changing on mobile for dark and light theme. This is an update to #1189.

Update to #1189

---

app/components/Modal/SendModal.jsx

- Make use of known scammer function on new send modal

Issue #981 - Send Modal Alert on known scammer

---

app/assets/locales/locale-en.json
app/assets/stylesheets/_shame.scss
app/assets/stylesheets/components/_modal.scss
app/assets/stylesheets/themes/_theme-template.scss
app/components/Modal/DepositModal.jsx

Fixes changes to modal SCSS code.
Few changes to _shame.scss code

Issue #969 - Final changes to Modal SCSS review

---

app/components/LoadingIndicator.jsx
app/components/Utility/LoadingButton.jsx
app/components/Utility/Tabs.jsx

Dear UI Team,
I have been developing a new page and the feedback for the user during loading tasks was just horrible (my own fault), or strenuous in development. For that purpose I have developed a LoadingButton component that allows visual feedback during such heavy tasks without the need for keeping a state in the parent component.
The button supports two styles right now, and the html within is probably a bit hacky, any and all feedback is welcome.
Style inside-feedback: When the user clicks, the loading indicator and some message is displayed within the button, the button width is kept constant (message might be cut):
Style right-feedback: When the user clicks, the loading indicator and message appears on the right side:
One could also think of a style that does a complete window …

New component: LoadingButton

---

app/api/apiConfig.js

add line 42:
{url: "wss://bitshares.nu/ws", location: "Stockholm, Sweden"},

Adding Sweden Node to Public list

---

app/assets/locales/locale-ja.json

locale-ja.json file updated (#1243 change reflected and other minor Japanese context fixing)

---

app/assets/stylesheets/components/_modal.scss
app/components/Modal/SendModal.jsx

- One modal had no padding
- Scam Alert message issues on send modal

Issue 969 - Fixes for modal issue on Market Tab

---

app/components/Dashboard/MarketsTable.jsx

#1256 Add an ability to star markets on dashboard

---

app/assets/locales/locale-en.json
app/assets/stylesheets/themes/_theme-template.scss
app/components/Account/AccountSelector.jsx

- Trigger for knownScammer
- Introduced global positive/negative theme compliant colors

Issue 981 - Update AccountSelector for knownScammer

---

app/assets/locales/locale-de.json
app/assets/locales/locale-en.json
app/assets/locales/locale-es.json
app/assets/locales/locale-fr.json
app/assets/locales/locale-it.json
app/assets/locales/locale-ja.json
app/assets/locales/locale-ko.json
app/assets/locales/locale-zh.json
app/components/Account/RecentTransactions.jsx
app/components/Blockchain/Operation.jsx

#450 Add transaction id to account activity

---

app/components/Account/AccountOverview.jsx

#1258 Add ability to sort Portfolio by QTY

---

app/assets/locales/locale-en.json
app/assets/stylesheets/components/_modal.scss
app/components/Account/AccountSelector.jsx
app/components/Dashboard/SimpleDepositBlocktradesBridge.jsx
app/components/Modal/BaseModal.jsx
app/components/Modal/DepositModal.jsx
app/components/Modal/SendModal.jsx
app/components/Modal/SettleModal.jsx
app/components/Modal/WithdrawModalNew.jsx

There where a few issues with the commit for modals, as the width didn't work due to a mistake in my previous PR. 
This PR also removes the large alert message in #981, and replaces it with a tooltip on AccountSelect.
- Fixes width issue with modals
- Removes "scam alert" message on send modal
- Adds tooltip to scam title on user tag

Fixes - Modal, SendModal and AccountSelect

---

app/assets/locales/locale-en.json
app/assets/stylesheets/components/_exchange.scss
app/components/Account/AccountDepositWithdraw.jsx
app/components/DepositWithdraw/openledger/OpenLedgerFiatTransactionHistory.jsx
app/components/Exchange/BuySell.jsx

- BuySell Header
- OpenLedger Gateway Component

Issue #1335 - Fixing Translation

---

app/assets/locales/locale-ja.json

Added translation for Openledger component and for the buy-sell box.

Added Openledger component and minor fix  #1335

---

app/components/Exchange/MyMarkets.jsx

#1337 - Resolve tab index issue in find markets

---

app/App.jsx
app/assets/locales/locale-en.json
app/assets/stylesheets/components/_all.scss
app/assets/stylesheets/components/_incognito.scss
app/assets/stylesheets/themes/_dark-theme.scss
app/assets/stylesheets/themes/_light-theme.scss
app/assets/stylesheets/themes/_midnight-theme.scss
app/assets/stylesheets/themes/_theme-template.scss
app/components/Layout/Incognito.jsx
app/lib/feature_detect/incognito.js

Resolves #1190 
Dismissible warning is displayed for wallet users in incognito.

#1190 - Show incognito warning for wallet users

---

app/assets/index-dev.html
app/assets/index-electron.html
app/lib/common/account_utils.js

1344- Remove references to transwiser

---

app/api/apiConfig.js

Maintained by me. Please help test.

Add API node api.bts.mobi

---

app/assets/locales/locale-en.json
app/components/Account/AccountAssetUpdate.jsx
app/components/Utility/AssetSelector.jsx

- Set current market pair as placeholder
- Deny updates to pair to the same asset
- Increase error space
Allow the passing of a defined `placeholder` parameter.

Issue #1420 - Update Asset Issue

---

app/components/Account/AccountSelector.jsx
app/components/Modal/IssueModal.jsx

Error in AccountSelector from IssueModal on open event
Error in IssueModal onSubmit event

Fix IssueModal modal submit button

---

app/components/Account/AccountSelector.jsx
app/components/Modal/IssueModal.jsx
app/components/Utility/TypeAhead.js

- IssueModal UI Fixes
- AccountSelector Logic Fixes
- Typeahead CSS Issue
- AccountSelector Logic Fixes
- Don't display previous input unless change has been made to it

Issue #1395, #1375 - Fixes to AccountSelector and IssueModal

---

app/help/en/introduction/wallets.md

Issue 1415 - Typo in help doc

---

app/components/Modal/WithdrawModalNew.jsx
app/lib/common/assetGatewayMixin.js

Minor fixes to modal and gateway related issues

---

app/components/Account/AccountAssetUpdate.jsx
app/components/Account/FundFeePool.jsx
app/components/Blockchain/Asset.jsx

1288 - Extract FundFeePool from AccountAssetUpdate and use it in Asset

---

app/api/apiConfig.js
app/components/Modal/DepositModal.jsx
app/components/Modal/WithdrawModalNew.jsx
app/lib/common/assetGatewayMixin.js
app/lib/common/gatewayMethods.js
app/lib/common/gateways.js

- The new GDEX API (called `gdex2APIs` in code)
- More changes from gateway specific code to dynamic gateway settings of new modals
- Adding minAmount, maxAmount to backedAsset

Issue 1276 - Enabling GDEX Gateway

---

app/assets/locales/locale-ru.json

Update russian locale

---

app/api/apiConfig.js

I'm happy to added a new public api node wss://wss.ioex.top .

Add a new api node : wss://wss.ioex.top

---

app/api/apiConfig.js

Add wss://btsfullnode.bangzi.info/ws

Add New API Node: wss://btsfullnode.bangzi.info/ws

---

app/components/Modal/DepositModal.jsx
app/components/Modal/WithdrawModalNew.jsx

- Withdraw Modal not loading without selected asset
- Deposit Address to large for modal

Fixes - Withdraw/Deposit Modal Fixes

---

app/assets/locales/locale-en.json
app/assets/locales/locale-ru.json
app/components/Exchange/OrderBook.jsx

Added missed transaction in orders book:
- Spread
- Latest
- No orders
- No bids

Added missed transaction in orders book

---

app/components/Blockchain/Transaction.jsx

Tested with all SELECT options including the specific datepicker.

Fix #1397 Order Expiration Display bug

---

app/assets/locales/locale-en.json
app/assets/stylesheets/components/_account.scss
app/assets/stylesheets/themes/_theme-template.scss
app/components/Account/AccountOverview.jsx
app/components/Account/NestedApprovalState.jsx
app/components/Account/NestedApprovalStateLib.jsx
app/components/Account/Proposals.jsx
app/components/Blockchain/ProposedOperation.jsx
app/components/Modal/ProposalApproveModal.jsx

1482 - Account page, Proposed transactions

---

app/components/Account/AccountOrders.jsx

Moving onClick event from Translation to Button component

Issue 1553 - Multiple Order Canceling Issue

---

app/App.jsx
app/assets/stylesheets/vendors/_all.scss
package-lock.json
package.json

I've integrated & tested bitshares-ui-style-guide. It works pretty fine.
I've used `<BodyClassName>` because some tooltips/modals of ant are placing on the end of the body so they are out of theme scope `<div className={props.theme}" >`.
Issue: #1580

#1580 Integrate bitshares-ui-style-guide

---

app/components/Account/AccountAssetCreate.jsx

Disable different precision error message when not creating PM

---

app/components/Exchange/TradingViewPriceChart.jsx
charting_library/static/base.scss
charting_library/static/darkTheme.css
charting_library/static/darkTheme.scss
charting_library/static/lightTheme.css
charting_library/static/lightTheme.scss
charting_library/static/midnightTheme.css
charting_library/static/midnightTheme.scss
package-lock.json

Screenshots:
Tested on MacOS:
@svk31 I've used scss files to be able use variables etc. but I've used my local tools to compile them to have separate scss files from main project.

#1484 TradingView restyle

---

app/assets/locales/locale-ru.json

Updating ru locale

---

app/assets/locales/locale-en.json

- Added 2 missed translations in exchange
eg. https://github.com/bitshares/bitshares-ui/blob/develop/app/components/Exchange/OrderBook.jsx#L805

Added missed translations (no orders, no bids)

---

app/actions/MarketsActions.js
app/components/Dashboard/MarketsTable.jsx
app/components/Exchange/MarketRow.jsx
app/components/Utility/MarketPrice.jsx
app/components/Utility/MarketStatsCheck.jsx

Closes #1380, similar approach might be possible for #1346

Closes #1380 - Messages after socket disconnect

---

app/App.jsx
app/AppInit.jsx
app/actions/BlockchainActions.js
app/assets/locales/locale-en.json
app/components/Layout/Footer.jsx
app/components/Settings/AccessSettings.jsx
app/routerTransition.js
package-lock.json
package.json

1407 reconnect strategy

---

app/assets/locales/locale-en.json
app/components/Modal/BorrowModal.jsx

Allow updating a margin called order according to new standards in BSIP-30

Issue 1577 - BSIP-0030 Implementation

---

app/api/apiConfig.js

Issue 1510 - Adding nodes

---

app/components/Layout/Header.jsx
app/components/Layout/HeaderDropdown.jsx

Resolves Issue #1682 
Missing functions on the new DropDown Menu in staging throws errors

[staging] Issue 1682 - Header DropDown Issue

---

app/components/Account/Proposals.jsx
app/components/Blockchain/ProposedOperation.jsx

Includes proposer account name on proposals

Issue 1674 - Include proposer account name

---

app/actions/AssetActions.js
app/components/Exchange/MarketPicker.jsx
app/components/Exchange/MyMarkets.jsx
package-lock.json
package.json

- Include backedAssets
- Min 3 char to initiate query
- Wait timer to reduce queries

Issue 1675 - Include Backed Asset in Find Market

---

app/assets/stylesheets/components/_account.scss
app/components/Exchange/MyOpenOrders.jsx

Reordered table columns
Dashboard Table right/left spacing
Cancel and Trade place first in table.

Issue 1667 - Dashboard Colum Reordering

---

app/components/Account/MarginPositions.jsx

Issue 1688 - Add Trading link to margin table

---

app/components/Blockchain/Transaction.jsx
app/components/Modal/BorrowModal.jsx

Delimiter issue as it should be by a factor of 1000

Fix Target CR Delimiter (Issue #1727)

---

app/lib/common/MarketClasses.js
app/test/marketTests.js

@abitmore I'd appreciate if you could look this over since I'm not sure it's correct. As mentioned before this stuff makes my brain hurt lol.

#1576: Add target collateral ratio to orderbook calculations

---

app/assets/locales/locale-de.json
app/assets/locales/locale-en.json
app/assets/locales/locale-es.json
app/assets/locales/locale-fr.json
app/assets/locales/locale-it.json
app/assets/locales/locale-ja.json
app/assets/locales/locale-ko.json
app/assets/locales/locale-ru.json
app/assets/locales/locale-tr.json
app/assets/locales/locale-zh.json
app/components/Account/AccountOrders.jsx
app/components/Account/AccountOverview.jsx
app/components/Account/AccountPortfolioList.jsx
app/components/Account/RecentTransactions.jsx
app/components/Exchange/MyOpenOrders.jsx
app/components/Explorer/Accounts.jsx
app/components/Explorer/Assets.jsx
app/components/Utility/PaginatedList.jsx

Also makes the portfolio sorting more reliable since I had to refactor it slightly.

Fix #1740: Add pagination to several tables

---

app/assets/locales/locale-en.json
app/components/Modal/BorrowModal.jsx

React Tooltip wasn't loaded properly

Fixes 1758 - Tooltip on Margin Modal

---

app/components/Exchange/MarketPicker.jsx

- Don't show bounce image if input isn't valid symbol
- Set inputValue state before we return false
This should also be merged to staging as it's present in 180815-RC1

Fixes 1788 - MarketPicker Issue

---

app/assets/stylesheets/themes/_theme-template.scss

- Changed colors to fit white theme better
- Including Going Through App to find other CSS related issues.

Issue 1753 - White Theme Fix

---

app/components/Account/AccountPortfolioList.jsx

#1818 Fix bitasset undefined options

---

app/assets/locales/locale-en.json
app/assets/stylesheets/themes/_theme-template.scss
app/components/Exchange/BuySell.jsx
app/components/Exchange/Exchange.jsx
app/components/Exchange/OrderBook.jsx

- BuySell Input styles
- Default to "My Market"
- Change "Quick Buy" to "Quick Deposit"
- Align group select
- Fix layout arrows
- Missing translations for gateways

Fixes #1822

---

app/assets/locales/locale-en.json
app/assets/stylesheets/themes/_theme-template.scss
app/components/Exchange/BuySell.jsx
app/components/Exchange/Exchange.jsx
app/components/Exchange/OrderBook.jsx

Reverts bitshares/bitshares-ui#1823

Revert "Fixes #1822"

---

app/components/Account/AccountAssetUpdate.jsx

See https://github.com/bitshares/bitshares-ui/issues/1539#issuecomment-419714431

remove bad default case in AccountAssetUpdate's onChangeBitAssetOpts

---

app/components/Account/AccountAssetUpdate.jsx

#1848 - Fix updating bitasset's minimum number of feeds

---

app/components/Blockchain/Asset.jsx
app/components/Blockchain/AssetPublishFeed.jsx

#1833 - Allow to publish pricefeed for any backing asset

---

app/assets/locales/locale-en.json
app/components/Account/Proposals.jsx
app/components/Blockchain/Operation.jsx
app/components/Blockchain/Transaction.jsx
app/components/Blockchain/operations.scss
app/components/Forms/AccountSelect.jsx
app/components/Modal/ProposalApproveModal.jsx

Reverts bitshares/bitshares-ui#1853

Revert "#1673 - Allow proposal_delete operation"

---

app/assets/locales/locale-en.json
app/components/Blockchain/Operation.jsx

Reverts bitshares/bitshares-ui#1851

Revert "#1785 - Add instant settlement description in account activities"

---

app/assets/locales/locale-en.json
app/components/Account/Proposals.jsx
app/components/Blockchain/Operation.jsx
app/components/Blockchain/Transaction.jsx
app/components/Blockchain/operations.scss
app/components/Forms/AccountSelect.jsx
app/components/Modal/ProposalModal.jsx

Reverts bitshares/bitshares-ui#1877

Revert "Revert "#1673 - Allow proposal_delete operation""

---

app/assets/stylesheets/themes/_theme-template.scss

#1881 Add no-background for assets tabs content

---

app/api/apiConfig.js

Adding list of nodes from the worker proposal

Updated node list by APAsia.tech

---

app/assets/locales/locale-en.json
app/assets/stylesheets/components/_header.scss
app/assets/stylesheets/themes/_theme-template.scss
app/components/Account/AccountDepositWithdraw.jsx
app/components/Layout/Header.jsx
app/components/Layout/HeaderDropdown.jsx
app/components/Transfer/Transfer.jsx

Closes #1479 
On the screenshots above, clicking on the Send/Deposit/Withdraw links opens the corresponding modal.

#1479 - Send/Deposit/Withdraw beta -> legacy

---

app/components/Account/AccountOverview.jsx

Add one colum

---

app/assets/stylesheets/style-guide-fixes.scss
app/components/Explorer/Assets.jsx

Tested on MacOS:
Issue #1816 
[Screenshots there](https://github.com/bitshares/bitshares-ui/issues/1816#issuecomment-426460427)

#1816 Assets Redesign

---

app/components/DepositWithdraw/DisableCopyText.js
app/components/DepositWithdraw/blocktrades/OpenledgerGatewayDepositRequest.jsx
app/components/DepositWithdraw/citadel/CitadelGatewayDepositRequest.jsx
app/components/DepositWithdraw/rudex/RuDexGatewayDepositRequest.jsx
app/components/DepositWithdraw/xbtsx/XbtsxGatewayDepositRequest.jsx
package.json

Fix of issue #1870
@sschiessl-bcp please before do merge:
1) Make fork of `react-copy-to-clipboard` repo
2) Replace link on `package.json` file to our fork 
We need this to prevent any future invasion by outside packages we use in our app development

#1870 Fix clipboard issue

---

app/api/apiConfig.js
app/assets/locales/locale-de.json
app/assets/locales/locale-en.json
app/assets/locales/locale-fr.json
app/assets/locales/locale-ko.json
app/assets/locales/locale-ru.json
app/branding.js
app/components/Account/AccountDepositWithdraw.jsx
app/components/DepositWithdraw/bitspark/BitsparkGateway.jsx
app/components/DepositWithdraw/bitspark/BitsparkGatewayDepositRequest.jsx
app/components/DepositWithdraw/bitspark/BitsparkWithdrawModal.jsx
app/help/en/gateways/spark.md
app/help/en/toc.md
app/help/ru/gateways/spark.md
app/help/ru/toc.md
app/lib/common/BitsparkDepositAddressCache.js
app/lib/common/BitsparkMethods.js
app/lib/common/gateways.js

Hi guys,
That is the PR for the Spark gateway for BTC & ETH. Both main and beta deposit & withdraw interfaces are tested and working, you can check it on our prod server: https://dex.bitspark.io/deposit-withdraw.
Let us know if something needs to be added/changed.

Add bitspark gateway

---

app/components/Exchange/ConfirmOrderModal.jsx
app/components/Exchange/Exchange.jsx

Screenshot: https://github.com/bitshares/bitshares-ui/issues/2034#issuecomment-431217957

#2034 Restore ConfirmOrder on Exchange and fix Sell

---

app/assets/locales/locale-en.json
app/components/Account/RecentTransactions.jsx
app/components/Blockchain/Operation.jsx

2016 display fee in account activity

---

app/App.jsx
app/actions/AccountActions.js
app/assets/locales/locale-en.json
app/assets/stylesheets/components/_header.scss
app/assets/stylesheets/themes/_theme-template.scss
app/components/Account/AccountBrowsingMode.jsx
app/components/Layout/Header.jsx
app/stores/AccountStore.js

#1089 Add AccountBrowsingComponent and handle user account change

---

app/components/Account/AccountAssetCreate.jsx
app/components/Account/AccountAssetUpdate.jsx
app/components/Account/AccountSignedMessages.jsx
app/components/Blockchain/TransactionConfirm.jsx
app/components/Settings/AccessSettings.jsx

Issue: #1968 
Nothing special, just replace Foundation switch for StyleGuide Switch

#1968 [Foundation Elimination] Switch

---

app/components/Exchange/BuySell.jsx

Remove hard-coded font-size in order form (buy/sell)

Closes #2073: Remove hardcoded font-size in Order Form 

---

app/components/Exchange/Exchange.jsx

Issue #2002 - Only load modals once requested

---

app/components/Explorer/Assets.jsx

HI people,
this PR fixes issue #2090, please check it.
Thank you in advance

Explore Assets - No sorting functionality (issue #2090)

---

app/components/InitError.jsx
app/components/Settings/AccessSettings.jsx
app/components/Settings/Settings.jsx
app/components/Settings/WebsocketAddModal.jsx
app/components/SyncError.jsx

Issue: #2056
Changes done:
- Restore `Remove Node` Modal
- Fix Node Name on `Remove Node` Modal (it was missed previously)
- Fix props for `WebsocketAddModal` in all places where Modal is used

#2056 fix add node modal

---

app/assets/stylesheets/components/_exchange.scss
app/assets/stylesheets/layout/_antd.scss
app/assets/stylesheets/themes/_theme-template.scss
app/components/Exchange/Exchange.jsx
app/components/Exchange/MyOpenOrders.jsx
app/components/Exchange/OrderBook.jsx

This PR solves the following submitted issues
- Input cell contrast
- Zebra Stripe Removal
- Groups
- Reduce cell padding
- Reduce overall widths of BUY/SELL input fields and labels
- Find markets is missing in tiny and small screen
**Time spent: 2 hours**

Issue #2020 - Exchange Design Fixes

---

app/components/Wallet/Backup.jsx

Closes #2097 - Resolve white screen issue

---

package.json

Themes checked:
Browsers checked:
Issue #2015
Commit on style-guide: https://github.com/bitshares/bitshares-ui-style-guide/commit/8cd3ca9627c596de51ccc7724837868f3eb4c2ac

#2015 Update version of bitshares-ui-style-guide

---

app/assets/stylesheets/base/_fonts.scss
app/assets/stylesheets/themes/_theme-template.scss

I tried to find the better way but it is the most simple and fast hotfix to keep all other parts safe. 
Issue: #2060

#2060 Fix broken ant item labels

---

app/assets/stylesheets/themes/_theme-template.scss

Quick remove of ant overrides
issue #2120

#2120 Remove hardcoded style-guide overrides

---

app/components/Dashboard/MarketsRow.jsx

#2123 Fix market staring

---

app/components/Modal/WithdrawModalNew.jsx

#2022 Check if number pasting parsing is save 

---

app/assets/stylesheets/themes/_theme-template.scss
app/components/Account/AccountBrowsingMode.jsx
app/components/Layout/Header.jsx

Closes #2129 - View Only Mode for Mobile on Browsing Accounts

---

app/assets/locales/locale-en.json
app/components/Exchange/OrderBook.jsx

Closes #2076 - Change translation for Market Depth on orderbook

---

app/components/Exchange/Exchange.jsx
app/components/Exchange/OrderBook.jsx
app/components/Exchange/Personalize.jsx

Closes #2152 - Fix Settlements, Personalize chart size, vertical order book issues

---

app/App.jsx
app/actions/SettingsActions.js
app/assets/locales/locale-en.json
app/assets/stylesheets/components/_exchange.scss
app/assets/stylesheets/themes/_theme-template.scss
app/components/Exchange/Exchange.jsx
app/components/Exchange/ExchangeContainer.jsx
app/components/Exchange/ExchangeHeader.jsx
app/components/Exchange/PriceAlert.jsx
app/components/PriceAlertNotifications.jsx
app/services/Exchange.js
app/stores/SettingsStore.js

Issue: #422 
Browsers checked:
Themes checked:
All screenshots are there: https://github.com/bitshares/bitshares-ui/issues/422#issuecomment-436109921

#422 Price Alert

---

app/components/Explorer/Accounts.jsx

Closes issue #2093 - Explore Accounts - Styleguide + Sorting Update

---

app/components/PriceAlertNotifications.jsx

#2181 Fix price alerts

---

app/components/Explorer/Assets.jsx

reference ticket -> https://github.com/bitshares/bitshares-ui/issues/2084

2084 search align

---

package.json

Closes #2197 
@sschiessl-bcp see comment - https://github.com/bitshares/bitshares-ui/issues/2197#issuecomment-441136393

#2197 Update bitshares-ui-style-guide version

---

app/assets/locales/locale-en.json
app/components/Account/AccountPortfolioList.jsx
app/components/Blockchain/Asset.jsx
app/components/Exchange/BuySell.jsx
app/components/Modal/SettleModal.jsx
app/components/Utility/withWorthLessSettlementFlag.jsx

- None BitAsset breaks page
- Remaining settleable volume percentage fix
- Translation (en)
Related to previous issue #1119

Fixes - Minor Fixes for Asset Details

---

package.json

Closes #2135 
StyleGuide commits:
https://github.com/bitshares/bitshares-ui-style-guide/commit/7431607d3642a65318d69fe982a0b7fb33e2ad18
https://github.com/bitshares/bitshares-ui-style-guide/commit/6943f0f5b08e1f56bd4357163ffef78613fe6a84

#2135 Update style-guide version. Add steps component support

---

app/components/Explorer/Assets.jsx
app/components/Settings/AccessSettings.jsx
app/lib/common/assetGatewayMixin.js

Closes #2100 
Fetches issuer name on sort and sorts by it

Issue 2100 - Sort Assets by Issuer Name on Explorer

---

app/assets/locales/locale-en.json
app/components/Blockchain/Asset.jsx
app/components/Blockchain/BidCollateralOperation.jsx
app/components/Utility/Tabs.jsx

Quick fix for renderCollateralBid()

Fixes renderCollateralBid() issue

---

app/components/Modal/DepositModal.jsx
app/components/Modal/WithdrawModalNew.jsx
app/lib/common/gatewayUtils.js

Closes #2259 
Enables withdraw of EOS.* assets for Open Ledger on the Gateway Modal

Enable EOS.* assets on withdraw

---

app/assets/locales/locale-en.json
app/assets/stylesheets/components/_forms.scss
app/components/Utility/AmountSelectorStyleGuide.jsx
app/components/Utility/AssetInput.jsx
app/components/Utility/AssetSelect.jsx

Continuation of https://github.com/bitshares/bitshares-ui/pull/2142
Changes in the CSS are here https://github.com/bitshares/bitshares-ui/pull/2272/commits/a68b88dffa5f7e7d905262c65df2b99dc29d7d81

#1927 - ANT AssetSelector replacement: add AssetInput and AssetSelect

---

app/components/Account/AccountDepositWithdraw.jsx
app/components/DepositWithdraw/blocktrades/BlockTradesBridgeDepositRequest.jsx
app/components/DepositWithdraw/winex/WinexGateway.jsx

Closes #2285 
- BlockTrades input/output coin pair failure fixed
- Disabled Winex, Citadel due to CORS issues crashing client

Issue 2285 - Fix Legacy WithdrawDeposit

---

app/assets/stylesheets/layout/_antd.scss
app/assets/stylesheets/themes/_theme-template.scss

Closes #2314 
Screenshot: https://github.com/bitshares/bitshares-ui/issues/2314#issuecomment-446458157

#2314 Remove ant inputs overrides on exchange

---

app/components/Exchange/MarketHistory.jsx

Closes #2336 
Catch empty market history data

Issue 2336 - Catch empty Market history data

---

CONTRIBUTING.md
README.md

Closes #2348 
Updated information

Updating README and CONTRIBUTING files

---

.github/PULL_REQUEST_TEMPLATE/with_visual_change.md
.github/PULL_REQUEST_TEMPLATE/without_visual_change.md

Closes #1939
Took 1 hours, evaluated different options of automation, but none were satisfactory
Signed-off-by: Stefan Schießl <stefan.schiessl@blockchainprojectsbv.com>

add pr template

---

app/App.jsx
app/components/Account/AccountVoting.jsx

Closes #2231 
Refactored the AccountVoting component to fill in props by itself.
Hours: 1

2231 voting shortcut

---

app/components/Exchange/BuySell.jsx

Closes #2375 
Fixes the missing market fee value on Exchange Order Form.

Issue 2375 - Missing market fee value on exchange form

---

app/assets/stylesheets/themes/_theme-template.scss

Issue #2355 - update style file

---

app/api/apiConfig.js

- Removed one of blckchnd API node - wss://node.market.rudex.org

Removed one of API node

---

app/components/Utility/DecimalChecker.jsx

Added null and empty string check for getNumericEventValue DecimalChecker.jsx
#2350

Issue #2350 PR

---

app/lib/common/paperWallet.js

Closes #2395
- reduced margin between barcodes
- correct naming of keys
- allow page break
Hours: 2

2395 paper wallet truncates at one page

---

README.md

Updated Readme for worker related status

Update README with Worker Status

---

CONTRIBUTING.md
README.md

Updated docs after the new worker passed

Updated development docs after new worker

---

app/components/Blockchain/Asset.jsx

Closes #2475 
Checks if feedPrice is null

Issue 2475 - Catch empty feedPrice on Asset

---

app/components/Layout/Header.jsx

Closes #2468 
Closes #2469 
Lazy loading Modals for Withdraw and Deposit fix
Has to be AND not OR to load the modal code.
Required 1 hour for testing and locating the problem.

Issue 2468,2469 - Fixes lazy loading for Modal

---

app/assets/index.hbs
app/assets/outdated_browser.css
webpack.config.js

Closes #2407
Unsupported messages is shown at the lowest HTML level
Hours: 4

2407 edge browser stuck on loading

---

app/components/Settings/AccessSettings.jsx

closes https://github.com/bitshares/bitshares-ui/issues/2500

safeguard for missing url

---

app/components/Dashboard/SimpleDepositBlocktradesBridge.jsx

- Implemented the new Style Guide components to the Buy Modal.
- Cleaned the code from redundant and/or unused code
Closes #2033
letse make sure the following is done: …

Issue 2033 - Antified Buy Modal

---

app/components/Exchange/Exchange.jsx

Closes #2233 
[fix for saving personalize settings, try to save personalize settings to test]
lease make sure the following is done:

#2233. fix for saving personalize settings

---

package.json

Closes #2550
```
import {DatePicker} from "bitshares-ui-style-guide"
```
API doc you can find there: https://ant.design/components/date-picker/

#2550 Update style-guide version

---

app/components/Account/AccountMembership.jsx

Closes #2539 
- Invalid URL format fixed
lease make sure the following is done:

Fix invalid linkage URL

---

app/help/en/index.md
app/help/en/introduction/hackthedex.md

- Add HackTheDex Section
- Add Github Link in Help Index
Closes #2027

Issue 2027 - Update Help Section to include Hack The Dex

---

app/assets/locales/locale-en.json
app/components/Modal/ReserveAssetModal.jsx

Issue 2581 - Asset Burn Alert notify

---

app/assets/locales/locale-en.json
app/components/Modal/SettleModal.jsx
app/components/Utility/withWorthLessSettlementFlag.jsx
app/routerTransition.js

Closes #2593 
- Display correct settlement price on Settle Modal
- Display asset settlement offset %
- Also removed console.log output

Issue 2593 - Asset Settlement Fixes

---

app/components/Utility/BindToChainState.jsx

introduce errorhandling for BindToChainState

---

app/components/Account/MarginPosition.jsx
app/components/Blockchain/Asset.jsx
app/lib/common/MarketClasses.js
app/stores/MarketsStore.js

Issue 2634 - Fixes for call_price changes in core

---

app/api/apiConfig.js
app/assets/locales/locale-en.json
app/assets/stylesheets/components/_account.scss
app/components/Account/AccountOverview.jsx
app/components/Account/AccountSelector.jsx
app/components/Account/RecentTransactions.jsx
app/services/AccountHistoryExporter.js

Closes #2543 
- Add modal on export button click
- Add textbox for es endpoint
- Add button for coinbase export
- Add button for full/raw export
- Add functionality for raw export
- Externalize export functionality into class
- Add English translations for new UI
Go to Activity tab, click export, and test both Coinbase and Full Report

Issue 2543 - Full Export & Modal

---

app/api/apiConfig.js

We deployed a new API node and requested to add it.

add btspp api node.

---

app/assets/stylesheets/components/_exchange.scss
app/assets/stylesheets/layout/_page_layout.scss
app/components/Exchange/DepthHighChart.jsx
app/components/Exchange/TradingViewPriceChart.jsx

- TV right padding
- Depth Chart Padding
- Increased form padding
Closes #2494

Issue 2494 - Exchange Padding

---

app/components/Exchange/Exchange.jsx

- Only pass custom order dates to the next market
Closes #2358

Issue 2358 - Exchange order expirations

---

package.json

Update css loader

---

app/assets/locales/locale-en.json
app/components/Blockchain/Transaction.jsx
app/components/Modal/ProposalModal.jsx

Closes #2527
- Show transaction costs are free is 0
- Preselect if only one present

#2527 Added label Free and added selected user if only 1 account exists

---

app/components/Account/RecentTransactions.jsx

#2545 Added new sortig parametrs

---

app/assets/locales/locale-en.json
app/components/Account/AccountVesting.jsx

Closes #2595
Added type as new row

#2595 Vesting balance type

---

app/assets/locales/locale-en.json
app/components/Account/AccountVoting.jsx
app/components/Account/WorkerApproval.jsx

Closes #2626
Refactor how workers are rendered, separate polls out. Should be antified and moved next to Workers in separate issue.
_Please provide screenshots/licecap of …

2626 add a (poll tab/function) to voting page

---

app/assets/stylesheets/themes/_dark-theme.scss
app/assets/stylesheets/themes/_light-theme.scss
app/assets/stylesheets/themes/_midnight-theme.scss
app/assets/stylesheets/themes/_theme-template.scss
app/components/Settings/Settings.jsx

Closes #2678
- Fix margins between settings entries
- Hardcode styles for ant form item labels for settings container

#2678 Fix settings design

---

package-lock.json
package.json

Closes #2293
- Update box-shadow for midnight and dark themes (make it stronger .15 opacity to .55)
See comment: https://github.com/bitshares/bitshares-ui/issues/2293#issuecomment-491210880
Style-Guide commits:
https://github.com/bitshares/bitshares-ui-style-guide/commit/7b3ef387dadbf25ab63b15894e90db4e3b8c5c4b
https://github.com/bitshares/bitshares-ui-style-guide/commit/83b82d056ca134b08521e8eca541438b7b4783f6

#2293 Update style-guide version

---

app/branding.js

Hi gents, sendind this PR in addition #1843.
Extra Bitspark assets included.

Add additional Bitspark assets

---

app/assets/locales/locale-en.json
app/components/Account/NestedApprovalState.jsx
app/components/Account/NestedApprovalStateLib.jsx

Closes #2288 
Added fail_reason message on hover on proposal object

Added fail reason on proposal fail in tooltip

---

app/api/apiConfig.js

Australia, Europe and Asia have been added. 
Total added with this commit: 10
Total operational from worker: 20

addition of new nodes from exotic infra worker

---

app/actions/AccountActions.js
app/assets/locales/locale-en.json
app/components/Account/AccountBrowsingMode.jsx
app/components/Settings/Settings.jsx
app/stores/AccountStore.js
app/stores/SettingsStore.js

Closes #2577 
Honor the "Never show" selection. Add new general setting "view only mode".

Issue 2577 - Honor the "view only mode" setting

---

app/components/Exchange/MyMarkets.jsx
app/components/Explorer/Assets.jsx
app/components/Utility/SearchInput.jsx

Closes #2698 
Added delete buttons in these places:
Explore -> Assets -> Filter ...
Exchange -> MY MARKET -> Filter
_Please provide screenshots/licecap of your changes …

Issue 2698 - add delete button for search inputs.

---

app/components/Account/AccountBrowsingMode.jsx
app/components/Layout/Header.jsx

Closes #2726 
Fix for updating dashboard with the new account data when click "View Mode".

Issue-2726. update dashboard when click "view mode"

---

app/assets/locales/locale-en.json
app/components/Account/AccountSelector.jsx
app/components/Utility/AssetSelect.jsx

Closes #2728 
Enable filtering
Changed placeholder
Disabled list, when only one asset is available

Issue-2728. fix for asset selector on Send modal

---

app/assets/stylesheets/themes/_dark-theme.scss
app/assets/stylesheets/themes/_light-theme.scss
app/assets/stylesheets/themes/_midnight-theme.scss
app/assets/stylesheets/themes/_theme-template.scss
app/components/Account/AccountOverview.jsx

#2705 Themes Fresh Up

---

app/components/Settings/Settings.jsx

#2757. resolve error in the settings menu

---

app/components/Exchange/MyOpenOrders.jsx

Closes #2764 
- Now aligned to the left.
- Checkbox update to style-guide.
- Checkbox logic improved

Issue 2764 - MyOpenOrder Improvements

---

app/assets/stylesheets/themes/_theme-template.scss
app/components/Blockchain/Asset.jsx

Closes #2779 
Reverts back to background colored notification on low margin positions.

Issue 2779 - Margin Table updates

---

app/components/Account/AccountBrowsingMode.jsx
app/components/Account/AccountPage.jsx
app/components/Layout/Header.jsx

Closes #2774 
Update dashboard when currentAccount is changing, clean up unused code

#2774. No dashboard switch when account is changing

---

app/components/Dashboard/MarketsTable.jsx

Closes #2765 
fix for volume sorting and 0 values

#2765. wrong volume list.

---

app/assets/locales/locale-en.json
app/assets/stylesheets/layout/_page_layout.scss
app/components/Account/AccountOverview.jsx
app/components/Blockchain/Asset.jsx
app/components/Exchange/MyMarkets.jsx
app/components/Explorer/Accounts.jsx
app/components/Explorer/Assets.jsx
app/components/Explorer/CommitteeMembers.jsx
app/components/Explorer/Witnesses.jsx
app/components/Layout/Header.jsx
app/components/Utility/SearchInput.jsx

Closes #2776
Closes #2775
Closes #2762
- Changed Input to Search input components
- Added sigma simbol instead of "cumulative"
- Added htlc header
- Increased "delete"  button tap area
_Delete this section if there weren't any UI changes. Please make sure you tested your changes in …

#122 refine release candidate 2776 2776 2777 2762

---

app/components/Account/MarginPositionsTable.jsx

Closes #2790 
change total balance column alignment

#2790. margin position alignment

---

app/components/Exchange/ScaledOrder.jsx
app/components/Exchange/ScaledOrderTab.jsx

Closes #2786
Changed toFixed to toPrecision to avoid rounding errors

#2786 Scaled trade doesn't work

---

app/components/Modal/WithdrawModalNew.jsx

Closes #2783 
Сommented code, which changed asset precision and was used in WIthdrawModalNew component for estimated value block. But this block was commented at 28.02.2018 by Calvin Froedge "Remove estimated value filed". If this block isn't used , part of the code can be removed. …

#2783. fix for price while withdrawing

---

app/components/Blockchain/operations/LimitOrderCreate.jsx

Closes #2801 
- Fixed typo on function call

Issue 2801 - Limit Order Create OP Typo

---

app/assets/locales/locale-de.json
app/assets/locales/locale-en.json
app/assets/locales/locale-es.json
app/assets/locales/locale-fr.json
app/assets/locales/locale-it.json
app/assets/locales/locale-ja.json
app/assets/locales/locale-ko.json
app/assets/locales/locale-ru.json
app/assets/locales/locale-tr.json
app/assets/locales/locale-zh.json
app/components/Blockchain/Asset.jsx

Closes #2903 
- Switching between cum and position fixes
- Updated translation to better description

Issue 2903 - Asset Margin Table updates

---

app/components/Account/AccountSelector.jsx

Closes #2813 
Set status to "Unknown member" if ChainStore.getAccountMemberStatus returns undefined

#2813. send to missing translation

---

app/components/Showcases/Barter.jsx

Closes #2873 
resolved issue with buffering wrong memo message

#2873. Barter, problem with entering amount

---

app/components/Blockchain/OperationAnt.js

Closes #2875 
remove decimalOffset for BTS(htlc create operation)

#2875. incorrect amount of locked BTS

---

app/components/Showcases/Borrow.jsx

#2926. selected borrowed asset issue

---

app/components/Account/AccountVesting.jsx
app/components/Modal/DirectDebitClaimModal.jsx
app/components/Modal/DirectDebitModal.jsx
app/components/Modal/HtlcModal.jsx

#2962 white screen

---

app/lib/common/scamAccounts.js

bitcoinindonesia is a legit exchange account.

Remove bitcoinindonesia from scamAccounts.js

---

app/components/Layout/Footer.jsx
app/components/Settings/AccessSettings.jsx
app/components/Settings/ResetSettings.jsx

- fixed accessSettings autoSelectAPI rendering
- Added connection update on reset settings
Closes #2888
https://github.com/blockchainprojects/bitshares-ui/pull/147

- Fixed footer autoSelectAPI rendering

---

app/components/Blockchain/Asset.jsx

Closes #2942
https://github.com/blockchainprojects/bitshares-ui/pull/163

Changed default market for bitassets

---

app/assets/locales/locale-en.json
app/components/Account/Proposals.jsx
app/components/Account/RecentTransactions.jsx
app/components/Blockchain/ProposedOperation.jsx

Raw json for account activities and proposal transactions

---

app/assets/stylesheets/components/_account.scss
app/assets/stylesheets/themes/_theme-template.scss
app/components/Account/AccountPortfolioList.jsx
app/components/Utility/CustomTable.jsx

Closes #2761 
Added !important rule to stretch size of dropdown menu.

Fix issue with jumping dropdown menu

---

app/components/Layout/Header.jsx
app/components/Settings/Settings.jsx

Closes #2921
https://github.com/blockchainprojects/bitshares-ui/pull/168

#2921 restore import missing translation

---

app/components/Modal/WithdrawModalNew.jsx

#2982. min, max withdraw(string compare issue)

---

app/components/Account/CreateAccount.jsx

Closes #3015 
There was wrong property name for password validation callback.

#3015. wallet mode, create account issue

---

app/api/accountApi.js
app/assets/locales/locale-en.json
app/components/Wallet/ImportKeys.jsx
app/components/Wallet/ImportKeys.scss
webpack.config.js

Closes #2837 
- Fix UI breakage in WIF key field
- Add error messages for incorrect WIF
- Add translations for error messages
- Display associated account(s) for WIF

2837-KeyImportFromWIF

---

app/components/Blockchain/ProposedOperation.jsx

Closes #3024
https://github.com/blockchainprojects/bitshares-ui/pull/187
Bounty request 0.25

Changed condition for proposed operation text

---

app/components/Account/AccountPortfolioList.jsx
app/components/Utility/BalanceComponent.jsx
app/components/Utility/EquivalentPrice.jsx
app/components/Utility/EquivalentValueComponent.jsx

Somehow got lost locally for ... #2690
- remove all refs
- clean up sorting mess
- refactor to strict value <> render logic
- introduce getFinalPrice

Missing commit for 2690

---

app/api/apiConfig.js

add new API node

---

app/actions/TransactionConfirmActions.js
app/assets/locales/locale-en.json
app/components/Blockchain/TransactionConfirm.jsx
app/components/Modal/JSONModal.jsx
package-lock.json
package.json

Closes #3040
https://github.com/blockchainprojects/bitshares-ui/pull/189
Also comes with a bitsharesjs PR
Hours spent: 09:15
Bounty request: 3.5

#3040 adapt error messages to new json rpc of bitshares core 3.2.0

---

app/api/apiConfig.js

https://bitsharestalk.org/index.php?topic=21569.msg337375#msg337375
>After being voted out for quite some time now. I have decided that I will be shutting down my api node in the next few days. Hopefully this should not have a large impact as there many more similarly located nodes now than when I had originally deployed it. I do apologize if this comes as an inconvenience. Should I be voted back and it is desirable, I will do my best to bring this node back online. My witness and seed nodes will continue to run to support the network. Thank you for your continuing support.

Comment out Lafona's API node

---

app/api/apiConfig.js

Update my bitshares node api url.

update my bitshares node api url

---

app/components/Exchange/OpenSettleOrders.jsx

Always view settle orders

---

app/branding.js

Remove Bridge tokens

---

app/branding.js

Remove SPARKDEX and BRIDGE

---

app/components/Account/AccountOverview.jsx

Remove OPEN.Assets from show always

---

app/assets/stylesheets/components/_header.scss

Removed margin-bottom for ul in status bar

remove margin for top-bar

---

app/assets/index.hbs
app/branding.js

just disable spellcheck in browser for better web performance

spellcheck off for web performance

---

app/lib/common/scamAccounts.js

added 2 more scam accounts that submit bs Proposals

---

app/components/Account/AccountPortfolioList.jsx

Collateral is not part of total value

---

app/api/apiConfig.js

Remove OpenLedger API

---

app/api/apiConfig.js

Add API node

---

app/api/apiConfig.js

add node api

---

app/lib/common/scamAccounts.js

Add "aaex-bitcny-deposit-wallet"

Add a new account to scam list

---

app/api/apiConfig.js

add API node nexus01.co.uk with correct regional setting (Northern Europe).
Public API server to compliment witness nexus01
additional node for wallet UI only
ok
ok
n/a
n/a

Add API node nexus01.co.uk

---

app/api/apiConfig.js

Remove API Node: wss://btsfullnode.bangzi.info/ws
_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all …

Remove API Node

---

app/lib/common/scamAccounts.js

Fixes https://github.com/bitshares/bitshares-ui/issues/3308

Add new accounts to scam list

---

app/api/apiConfig.js

Remove a dead API node

---

app/lib/common/scamAccounts.js

```
"bts-binance-1",
"1.2.1037039"
```
Ref: https://bitsharestalk.org/index.php?topic=32788.msg344654#msg344654

Add a new account to the scam account list

---

app/lib/common/scamAccounts.js

Add Binance Scam Account

---

app/components/Wallet/WalletUnlockModalLib.jsx

Other projects, similar issue:
https://github.com/lingui/js-lingui/issues/655
https://github.com/facebook/react/issues/13699

fix [object Object] bug

---

app/api/apiConfig.js
app/components/DepositWithdraw/gdex/GdexAgreementModal.jsx
app/components/DepositWithdraw/gdex/GdexGateway.jsx
app/lib/common/gateways.js

Fix connection issues likely caused by the GFW. See https://bitsharestalk.org/index.php?topic=33073.0 for more info.
_Please provide screenshots/licecap of your changes …

Update GDEX domain names

---

app/components/Layout/Footer.jsx

The old download link no longer works (although it may get fixed at some point). This PR replaces it with a direct link to Github.
By the way, ideally this download link and other links in the same source file E.G. the one used to check for updates should be in `branding.js`. But it would be a bigger change thus worth a new pull request IMHO.
https://github.com/bitshares/bitshares-ui/blob/fce189a88ddf5b1bb2e9dc6210dee10fb7343dfa/app/components/Layout/Footer.jsx#L114
https://github.com/bitshares/bitshares-ui/blob/fce189a88ddf5b1bb2e9dc6210dee10fb7343dfa/app/components/Layout/Footer.jsx#L495
_The branch has been tested on the following browsers (desktop and mobile …

Update download link

---

app/components/Exchange/MarketPicker.jsx
app/components/Utility/AssetName.jsx
app/lib/common/gatewayUtils.js

fix Market Picker crash on cancel

---

app/api/apiConfig.js

change gbac-ety001 api node url

change gbac-ety001 api node url

---

app/api/apiConfig.js

replace btspp-witness api address

replace btspp-witness api address

---

app/components/Blockchain/OperationAnt.js

fix White screen #3434

---

app/components/PrivateKeyView.jsx

<h2>Fix broken image in private key viewer.</h2>
Closes #3438

Fix broken image in private key viewer #3438

---

.github/workflows/npm-build-and-deploy-develop.yml
app/assets/stylesheets/components/_exchange.scss
app/assets/stylesheets/themes/_theme-template.scss
app/components/Exchange/OrderBook.jsx
app/components/Utility/TransitionWrapper.jsx
appveyor.yml
package.json
yarn.lock

<h2>fix K line setting bug</h2>
Closes #3447

fix K line setting bug #3447

---

app/actions/AssetActions.js
app/assets/locales/locale-en.json
app/components/Account/AccountAssetCreate.jsx
app/components/Account/AccountAssetUpdate.jsx
app/components/Blockchain/Asset.jsx
app/components/PredictionMarkets/CreateMarketModal.jsx

Rebase of https://github.com/bitshares/bitshares-ui/pull/3419

Taker fee rebased

---

app/assets/stylesheets/components/_exchange.scss

.borrow-price-label alignement

---

.github/workflows/npm-build-and-deploy-staging.yml

For https://github.com/bitshares/bitshares-ui/issues/3302#issuecomment-781499052

Create workflow for staging auto-deployment

---

app/api/apiConfig.js

update gbac-ety001 api node uri

update gbac-ety001 api node uri

---

app/api/apiConfig.js

Sorry, change gbac-ety001 api node uri again.

Sorry, change gbac-ety001 api node uri again.

---

app/assets/locales/locale-en.json
app/components/Blockchain/Asset.jsx
app/components/Utility/AssetName.jsx
app/stores/GatewayStore.js

Addresses https://github.com/bitshares/bitshares-ui/issues/3457
Current approach: Show disclaimer if not core token or issuer is not committee.

Add asset disclaimer and honor blacklist 

---

app/components/Utility/TranslateWithLinks.jsx

Please check the screenshots below.
Without the change (mainnet):
With the change (mainnet):
Without the change …

Add separators for account update ops in proposals

---

app/components/Blockchain/OperationAnt.js

This bug leads to a white screen in the UI.
Closes #3469

fix amm history bug

---

app/api/apiConfig.js
app/assets/locales/locale-en.json
app/branding.js
app/components/Modal/DepositModal.jsx
app/components/Modal/WithdrawModalNew.jsx
app/lib/common/gateways.js

can be tested over: https://bts.exchange

ioxbank gateway

---

app/assets/locales/locale-en.json
app/assets/locales/locale-zh.json
app/components/Blockchain/Asset.jsx
app/lib/chain/asset_constants.js
app/lib/common/asset_utils.js

add asset new properties

---

app/components/Account/CreditOffer/CreditOfferPage.jsx

<h2>Fix inaccurate floating point numbers used in credit offers</h2>
Closes #3487

Fix inaccurate floating point numbers used in credit offers

---

app/actions/CreditOfferActions.js
app/assets/locales/locale-en.json
app/assets/locales/locale-zh.json
app/components/Account/CreditOffer/CreditOfferList.jsx
app/components/Account/CreditOffer/CreditOfferPage.jsx
package.json
yarn.lock

<h2>Standardized time display</h2>
Closes #3490

Fix credit offer repayment period "No limit" #3490

---

app/components/Account/CreditOffer/CreditOfferPage.jsx

<h2>Fix inaccurate floating point numbers used in credit offers</h2>
Closes #3487

Fix inaccurate floating point numbers used in credit offers #3487

---

app/lib/common/MarketClasses.js

fix mcfr bug

---

app/stores/AddressIndex.js
app/stores/WalletDb.js

I faced error while trying to import private key.

Private key import fix

---

app/api/apiConfig.js

Added an API node located in North America, wss://api.bitshares.info

Adding api.bitshares.info api node

---

app/assets/locales/locale-en.json

Fine tuning

---

README.md
README_zh.md

chore: update readme

---

app/components/Layout/MenuDataStructure.js

For promotion.
Related: https://github.com/bitshares/bitshares-ui/issues/3512.

Add liquidity pools to top menu

---

app/actions/AssetActions.js

Fixing Float-to-Integer in collateral bidding

---

app/api/apiConfig.js

Addition of my testnet API node

Add iamredbar testnet API node

---

app/components/Exchange/OrderBook.jsx

Display market depth in OrderBook

---

app/components/Account/CreditOffer/CreateModal.jsx
app/components/Account/CreditOffer/EditModal.jsx

**Issue** #3566 
- As mentioned in the issue, if the user tries to add duplicated collateral - the previous one will be updated with the new amount
Closes #3591

#3566 Fix duplicates in collateral for credit offers

---

app/components/Account/CreditOffer/CreditOfferPage.jsx

#3565 Process borrow calculations on amount changed by click on total balance

---

app/components/Showcases/Borrow.jsx

added HONEST branded MPA asset ids to borrowing spotlight

Add HONEST to Borrowing Spotlight

---

app/branding.js

added to getFeaturedMarkets  
added to honestTokens
_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all …

add HONEST tokens to branding

---

app/assets/locales/locale-en.json
app/components/Account/CreditOffer/CreateModal.jsx
app/components/Account/CreditOffer/EditModal.jsx

**Issue** #3533
- This PR is based on this one - https://github.com/bitshares/bitshares-ui/pull/3591 
- Catch & detect overflow issues and display a user-friendly error (for create & edit)
- Add min_loan > total_balance error (for create & edit)
Closes #3533

#3533 Feature credit offer overflow validation

---

app/api/apiConfig.js

Addition of my testnet API node

added URL for Crypto Ninja node on testnet

---

app/api/apiConfig.js

Updating api node location to wss://api.bitshares.loclx.io

API node address update for bitshares.info

---

app/assets/locales/locale-en.json

Closing #3582 Missing locale string when creating vote lock

---

app/api/apiConfig.js

Removed my testnet API node. I am shutting the server down.

remove my testnet API node

---

app/api/apiConfig.js

Bhuz asked to remove his API node.

Remove Bhuz's API node

---

app/api/apiConfig.js

Remove an API node as requested.

Remove an API node

---

app/help/en/gateways/ioxbank.md

ioxbank gateway updated minimum amount to 10 XRP.
Official Reference: https://ioxbank.com

Update ioxbank.md for changing Min. amount: 10 XRP
